### ISSUE TITLE
"GitLens: Open File on Remote" opens wrong Bitbucket URL

### ISSUE THREAD

**Issue by halilim** [eamodio/vscode-gitlens#1006]
- GitLens Version: 10.2.1
- VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
- OS version: Darwin x64 19.4.0

Steps to Reproduce:

1. ```
   git clone https://bitbucket.org/atlassian/bitbucket-server-example-plugins.git
   cd bitbucket-server-example-plugins
   git checkout release/4.0
   code .
   ```
2. Open .gitignore and select lines 2 & 3
3. Cmd+Shift+P > GitLens: Open File on Remote

Actual:

https://bitbucket.org/atlassian/bitbucket-server-example-plugins/src/release/4.0/.gitignore#.gitignore-2:3 (404)

Expected:

https://bitbucket.org/atlassian/bitbucket-server-example-plugins/src/df3d81742268cd6ce91b1bc53d8611d701aab2fc/.gitignore?at=release%2F4.0#lines-2:3

**Comment by nerdmax** [comment]
I guess the issue is, gitlen is composing the URL with the branch name, while bitbucket wants the commit id.

So, if we change the URL's branch name(release/4.0) to commit id(df3d81742268cd6ce91b1bc53d8611d701aab2fc), it will work.

e.g.:
bitbucket.org/atlassian/bitbucket-server-example-plugins/src/release/4.0/.gitignore#.gitignore-2:3 not working
https://bitbucket.org/atlassian/bitbucket-server-example-plugins/src/df3d81742268cd6ce91b1bc53d8611d701aab2fc/.gitignore#.gitignore-2:3 working fine

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by halilim** [comment]
Can confirm v11.2.0 fixed it (should I still check the insider edition?). Thanks!

**Comment by eamodio** [comment]
@halilim Nope, thanks so much!
