### ISSUE TITLE
Avoid `⎇ + any` shortcuts because of conflicts with different keyboard layouts

### ISSUE THREAD

**Issue by robsonpeixoto** [eamodio/vscode-gitlens#104]
The keybind bellow are very useful for languages that use a lot a accents, like portuguese.
IMO it should be avoided.

⎇ + c = ç
⎇ + e = ´ (accent)
⎇ + ` = ` (accent)
⎇ + n = ˜ (accent)
⎇ + i = ˆ (accent)
⎇ + u = ¨ (accent)

It's just a suggestion. I know that's possible remove this keybind and I'm already did it.

**Comment by lindskogen** [comment]
In general, `⎇` is not a modifier key for commands on macOS, it should only be used for special characters.

**Comment by aeinbu** [comment]
Also on Scandinavian macs (at least Norwegian) SHIFT+⎇+7 is used for \ (Backslash)

**Comment by larsboldt** [comment]
With gitlens active I can no longer type backslashes in VSCODE because it triggers search, ref: SHIFT+⎇+7

Is it possible to reassign this?

**Comment by eamodio** [comment]
@larsboldt  you can specifically remove a shortcut key -- see https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

I think you just need to add the following to remove that key-binding:
```json
{
	"key": "alt+/",
	"command": "-gitlens.showCommitSearch"
}
```

**Comment by eamodio** [comment]
Since the `alt` modifier causes issues for some keyboard layouts -- what would people recommend as an alternative. Picking shortcuts keys is seemingly impossible to get right :)

**Comment by svenax** [comment]
I'd suggest to never use `alt` or `shift+alt` as modifiers, but instead always combine with `ctrl` and/or   `cmd`. For an extension that introduces many key commands, I'd prefer to see chorded shortcuts using a common starting shortcut. Since VS Code itself only uses `cmd+k` in this way, perhaps Gitlens could use `cmd+g`, e.g. `cmd+g c` for "Show commit details".

**Comment by eamodio** [comment]
Honestly I'm all for chords -- but I couldn't find any reasonable chords that didn't conflict with current vscode shortcuts or very popular extensions. It's like whack-a-mole. :(

**Comment by svenax** [comment]
Yes, it is a mess ... I've always wondered why other editors don't handle this in the same way as Textmate does, i.e. if several commands use the same shortcut, then all of them will be shown in a pick list with automatically assigned completions (1-9 as far as I remember). Anyhow, `cmd+alt+g` seems to be free as chord starter - or maybe it is taken by some other extension?

**Comment by eamodio** [comment]
It would also be nice if there was some way or something where I component could offer alternative keyboard mappings -- so maybe all the `alt+` works for some (i.e. me) and some alternative mappings could be offered as options. Since shortcut mappings for extensions are defined in the `package.json` it isn't even currently possible for extensions to offer any settings for alternatives.

I will look into the feasibility of alternates -- `cmd+alt` might work, would have to see how that translates on windows too.

**Comment by eamodio** [comment]
@robsonpeixoto @lindskogen @aeinbu @larsboldt @svenax @BendingBender @christophberger @chabou

I'm looking at trying to resolve this, but I want to request some help. So right now I'm thinking of adding a new `gitlens.keymap` setting to control which "keymap" to use. Thinking there will be 3 options, `default`, `alternative` (needs a MUCH better name), `none` -- it will default to `default`, and `alternative` needs to be figured out (that's where I would like some help), and `none` which will stop GitLens from adding any shortcut keys

So could you all help me come up with a reasonable (cohesive) set of alternative shortcut keys that have a much less change of a) causing issues with different keyboard layouts and b) don't conflict with other popular extensions

**Comment by eamodio** [comment]
Let's make sure we fix this too: https://github.com/eamodio/vscode-gitlens/issues/113

**Comment by robsonpeixoto** [comment]
I like this approach, @eamodio. It'll keep working for users that are familiarised with the keymaps, and will add an option to disable

**Comment by eamodio** [comment]
See `gitlens.keymap` setting under https://github.com/eamodio/vscode-gitlens/blob/master/README.md#general-settings
