### ISSUE TITLE
Cannot "open Repository/Branches/Branch on remote" when remote is not github

### ISSUE THREAD

**Issue by liangjiancang** [eamodio/vscode-gitlens#1095]
For example, when there is only one remote: `https://gitee.com/a/b.git`, you can't open anything on remote.

If you have two remotes: `https://github.com/a/b.git` and `https://gitee.com/a/b.git`, you can open the `gitee` remote, but the url is `github`. The key point is, there must be an origin of github.

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by liangjiancang** [comment]
Yes, it does.

After clicking "Open Repository on Remote":
![11](https://user-images.githubusercontent.com/42267675/100708922-21f3ff00-33e8-11eb-9d9a-8cda0d86317e.jpg)

**Comment by eamodio** [comment]
I believe the issue is that GitLens can't auto-detect your `gitee.com` remote, so it needs to be configured first. I have pushed a "fix" for this in the insiders edition of GitLens -- where you'll get a better error message.

Can you please try the insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by liangjiancang** [comment]
Sorry, I don't have much time for testing. You say GitLens can't auto-detect the `gitee.com` remote, but obviously it "knows" what the remote url is. I don't know what "detect" means, I just want to open the remote url in browser quickly, rather than an error message.
![2](https://user-images.githubusercontent.com/42267675/100716563-d7787f80-33f3-11eb-894f-ae368d1218c9.jpg)

**Comment by eamodio** [comment]
GitLens knows the git remote "url", but that doesn't provide enough information to be able to open a specific resource (branch, commit, file, etc) given that url (never mind that the git url could be git: or ssh: rather than http).  So in order for GitLens to be able to open those resources it needs to know how to form those urls -- and those need to be added via the `gitlens.remotes` setting.

**Comment by liangjiancang** [comment]
I get it, thanks for your reply. I don't have time to test it, but as long as the error message points to `gitlens.remotes`, it should be OK.
