### ISSUE TITLE
If a file's last modification only deleted lines (and didn't add any) that last modification time of the file is incorrect

### ISSUE THREAD

**Issue by jackureu** [eamodio/vscode-gitlens#1100]
Steps to Reproduce:

1. Take an existing file in a repository.
2. Modify it by deleting lines. Do not add anything
3. Look at the title of the file

See the following example:

![image](https://user-images.githubusercontent.com/41803181/91292880-d229ea00-e79f-11ea-9522-02df3358b2da.png)

This is incorrect as the file was also modified a few days ago.

**Comment by eamodio** [comment]
Unfortunately, this is a known limitation. Since the dates, etc are calculated from Git blame, and blame only works against the current set of lines (so deleted lines aren't considers). I've tried a few alternatives to attempt to deal with this, but I have yet to come up with a solution that works and is not EXTREMELY expensive to execute. Sorry.
