### ISSUE TITLE
`gitlens.currentLine.scrollable` setting does the same thing as the `gitlens.hovers.enabled` setting, with inexplicable hover control

### ISSUE THREAD

**Issue by liby** [eamodio/vscode-gitlens#1114]
- GitLens Version: 10.2.2
  
- VSCode Version: 1.49.1
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1.  Set `gitlens.currentLine.scrollable` setting: `"gitlens.currentLine.scrollable": false`. Actually, this is the default setting.
2. The following features are disabled: 
     > Detailed blame information accessible via hovers

Other:

It seems that `"gitlens.currentLine.scrollable": false` plays the same role as `"gitlens.hovers.enabled": false`.

Recording screen:

![hover-demo](https://user-images.githubusercontent.com/38807139/94095531-8167e880-fe54-11ea-9de3-d178edc3466c.gif)

**Comment by eamodio** [comment]
While those 2 settings are not actually related, they can appear to be.

`"gitlens.hovers.enabled": false` will just turn off the hovers when the mouse is over any blame annotations.

`"gitlens.currentLine.scrollable" = false` is kind of a hack setting to deal with issues the current line annotations can cause with word wrapping. Since by default, the current line blame annotations will cause the editor to scroll horizontally if they are outside the viewport. Unfortunately, by setting this, it also disables the hovers on the annotation itself (because they are now out of the document flow and won't receive hover events). By setting `"gitlens.hovers.currentLine.over": "line"` you can get the hovers back, by hovering anywhere over the line.

Hope that helps.

**Comment by liby** [comment]
@eamodio 
Even if, as you say, they are irrelevant, the problem is real.
I think it is an arbitrary act to close the problem if the problem is not solved.
After all, I gave the screenshot and reproduced the problem, but your answer did not solve the actual problem.

**Comment by eamodio** [comment]
As I mentioned -- `"gitlens.currentLine.scrollable" = false` is a hack, and can't be fixed (because of technical limitations of the vscode decoration api). So the only option, if you want to use `"gitlens.currentLine.scrollable" = false`  is to also set `"gitlens.hovers.currentLine.over": "line"` otherwise you will only be able to see the hovers if you mouse is exactly at the end of the line.

**Comment by liby** [comment]
I didn't read it carefully just now. I see what you mean. Thank you for your answer. It's very detailed.
Please forgive my carelessness and offense. I wish you a happy day.  🙏

**Comment by eamodio** [comment]
No worries at all!
