### ISSUE TITLE
Add an option for the codelens to ignore unsaved and uncommited changes

### ISSUE THREAD

**Issue by reednj** [eamodio/vscode-gitlens#112]
The codelens information that appears above blocks and at the top of files is really useful, but it disappears when there are any unsaved changes. This is not that useful I think - I would like to still be able to see the last commiter etc, even if I have unsaved changes in the file.

If I created a pull request to add an option to change this, is it likely to be accepted?

**Comment by eamodio** [comment]
@reednj I used to "support" this case, but fixed it, because there isn't any way to call git blame on unsaved changes -- so when editing the cached blame will likely be wrong. For example, just adding a single line near the top of the file will break the blame for the whole file (because the line numbers will be off by the newly added line).

If there is a way to keep the blame *working* in this case, I am all ears.

**Comment by reednj** [comment]
Oh yeah, you're right, its more complicated than I thought... you somehow
would need to save the blame information and then offset it based off lines
added / removed?

**Comment by eamodio** [comment]
@reednj I did some more research into this and it looks like you can pass in *file contents* into `git blame` using `--contents - <file contents here>`. I have yet to really try it out to see if it work, but if so, it **might** be possible to get this to work. If it works, the biggest caveat I see is triggering blames while you are typing would be **bad**, but even a decently debounce delay could also still feel like too much is going on.

**Comment by eamodio** [comment]
@reednj I've **finally** added experimental support to provide blame annotations, code lens, etc on unsaved (i.e. dirty) files. To try it out, please install the [7.3 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.3.0-beta) and make sure to set `"gitlens.insiders": true`

Let me know what you think! I think it provides a much smoother and richer experience.
