### ISSUE TITLE
Sorting is lost once you start filtering

### ISSUE THREAD

**Issue by jasonwilliams** [eamodio/vscode-gitlens#1144]
I have a lot of branches that are  from `origin` and `upstream` remotes.
I want to filter down to `origin` branches then still sort by date.

The sortByDate stops working once i set a filter.
If all the branches match the filter evenly, sort those remaining branches by the original sort.

- GitLens Version: 10.2.3
  
- VSCode Version: 1.51
- OS Version: 10.15.6

Steps to Reproduce:

1. Set `"gitlens.sortBranchesBy": "date:desc"` in your settings
2. filter branches by `origin/`

The sorting is lost.

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by jasonwilliams** [comment]
@eamodio yes this still happens on 11.0.1. Once I add a filter it switches to alphabetical order. My use case is I want to filter out remote branches, so I add “origin/“ as a filter.

**Comment by jasonwilliams** [comment]
I’ve added all the info I need here.

**Comment by eamodio** [comment]
Sorry but I can't reproduce this -- I tried this on the VS Code repo, sorted by date, descending, and when I filter the date ordering is preserved.

Can you show me what you are seeing?

**Comment by jasonwilliams** [comment]
Here's some examples @eamodio 

<img width="893" alt="dateOrdering" src="https://user-images.githubusercontent.com/936006/102994316-be587f80-4516-11eb-96ef-1481cb52374d.png">

![image](https://user-images.githubusercontent.com/936006/102994382-e0ea9880-4516-11eb-8049-b306a1fe859e.png)


You can see it sorts alphabetically regardless what I set in my settings

**Comment by eamodio** [comment]
@jasonwilliams Oh you are talking about in the quick picks -- I thought you meant the views.

So, I just fixed a few issues where the branch/tag sort setting wasn't getting honored properly. I also added an indicator (star) when a branch was favorited (because that bumps it up in the sorting regardless of the setting).

But as for the filtering changing the order, that again is controlled by VS Code, so I would recommend reporting it there.
