### ISSUE TITLE
Connect to Github notification is noisy

### ISSUE THREAD

**Issue by sandy081** [eamodio/vscode-gitlens#1208]
I am always seeing following notification when settings sync install Gitlens

<img width="459" alt="image" src="https://user-images.githubusercontent.com/10746682/100151643-bb2f8c80-2ea1-11eb-8c07-3b284d2375e2.png">

Accounts icon already shows a number badge for this

<img width="430" alt="image" src="https://user-images.githubusercontent.com/10746682/100151800-fa5ddd80-2ea1-11eb-9b36-8c0dd782c7a9.png">

So not sure if the notification is needed.

**Comment by moshfeu** [comment]
Or, at least, add an option "don't show again" or something..

**Comment by eamodio** [comment]
When are you seeing this? I would only expect it to show once, if you accept, for each machine (since I don't think we sync the auth). And once for each workspace, if you reject.

@sandy081 The reason I am showing this notification, is because without it the user just gets an allow authentication access prompt (from the built-in vscode auth) and they wouldn't know why.

**Comment by moshfeu** [comment]
Now that I checked, I think one time for each project.

**Comment by eamodio** [comment]
@moshfeu are you rejecting? or accepting?

**Comment by moshfeu** [comment]
Rejecting 😳

**Comment by eamodio** [comment]
Ah, so you want an always reject? Curiously, why don't you want it to connect to GitHub?

**Comment by moshfeu** [comment]
For now.. I use to reject requests until I need the feature. Nothing personal :)

**Comment by eamodio** [comment]
No worries, just curious. And FYI, the connection provides many passive features -- GitHub avatars, richer issue linking in hovers, rich PR linking in views, hovers, and annotations.

**Comment by moshfeu** [comment]
Thanks! I really like this extension and I'll probably connect Github soon.

**Comment by the-exodus** [comment]
> Ah, so you want an always reject? Curiously, why don't you want it to connect to GitHub?

Personally, I opted out once I saw the permissions requested 🤯

**Comment by flmn** [comment]
I have the same question.
I just want to see blame message from git history, I don't want to see pull requests or something else.
Can provided an global option to disable connect to GitHub, if anyone want to disable it, just opt out.

**Comment by saveriomiroddi** [comment]
Hello, experiencing the same. I keep getting notified on each VSC start, and it's irritating.

I also find the "Cancel" option (button) confusing, but this is a general UX design problem: does it mean "confirm negative intention" (in this case, don't show warning anymore), or "close widget without applying any change" (in this case, show warning again next time)?

Use case: my usage of GitLens is very limited, as I'm a heavy terminal user; additionally, as a general systems administration practice, I don't give permissions to services I don't require. Therefore I don't benefit from authorizing a remote connection.

**Comment by eamodio** [comment]
Yeah, I will definitely be adding a way to completely opt-out soon. Sorry for the inconvenience.

**Comment by saveriomiroddi** [comment]
> Yeah, I will definitely be adding a way to completely opt-out soon. Sorry for the inconvenience.

Thank you for the addon, it's impressive! :smiley:

**Comment by sandy081** [comment]
@eamodio 

> The reason I am showing this notification, is because without it the user just gets an allow authentication access prompt (from the built-in vscode auth) and they wouldn't know why.

I think auth feature of VS Code shall be able to handle the UI instead of each extension come up with its own. I would request not to do this (any custom UI or notifications for authentication) instead please raise your concerns with auth feature to handle your request. 

@RMacfarlane FYI

**Comment by jasonwilliams** [comment]
It's showing every time I open a new workspace for me.

**Comment by MaerF0x0** [comment]
> why don't you want it to connect to GitHub?

The requested authorization is WAY too permisive

![Screen Shot 2020-11-30 at 3 31 19 PM](https://user-images.githubusercontent.com/247846/100678049-27d2dd00-3321-11eb-9f08-2c86fd10f1bf.png)

This is much different than allowing me to initiate and control actions from my machine (via ssh keys etc) .  Wont this generate an authorization that can me used offline, from their servers, without additional consent/initiation?

**Comment by eamodio** [comment]
@MaerF0x0 Unfortunately currently the VS Code authentication APIs (because of limitations with GitHub auth) don't allow for any permission scopes less permissive than what I'm currently asking for (the `repo` scope) -- I wish I could just ask for read-only access, but that isn't currently possible.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

I've reworked the notifications a bit to be clearer and added a "don't ask me again" type option. Unfortunately there still is 1 extra notification in certain cases, but that is because of https://github.com/microsoft/vscode/issues/111529. So once that gets fixed I can remove it.

**Comment by MaerF0x0** [comment]
@eamodio  is it possible that I can generate my own token w/ pared down scopes to provide to the plugin via the settings.json?

**Comment by eamodio** [comment]
I believe so -- during the VS Code auth flow (when it opens the browser window), I believe there is an entry in the statusbar that you can click that will prompt for a PAT.  But I don't believe you can create a PAT with any less scopes than I am currently asking for -- because repo info, prs, issues etc are all under the `repo` scope.

**Comment by MaerF0x0** [comment]
@eamodio try checking out the personal access token new page, there are lots and lots of options... I understand that vscode maynot have the hooks to allow you to generate one for us, but maybe we could just generate a limited access one to use? 

https://github.com/settings/tokens/new

**Comment by eamodio** [comment]
Yes, but as I said -- the ONLY scope on that page that lets you get to repository information -- including PR & Issues -- is the `repo` scope -- and there is nothing more granular. If there was -- I would be asking for it -- since those are the exact same set of scopes I am choosing from.

**Comment by jasonwilliams** [comment]
> @eamodio is it possible that I can generate my own token w/ pared down scopes to provide to the plugin via the settings.json?
> 
> to be honest I basically use gitlens in a read only fashion -- to see git praise, to check out branches, commit log etc.
> 
> That way it can only run from my machine too?

I raised https://github.com/eamodio/vscode-gitlens/issues/1210 for exactly this. It’s not possible for us to use the authentication feature because we’re on enterprise and VSCode takes me to GitHub.

**Comment by eamodio** [comment]
The VS Code team is trying to auth with GitHub using a GitHub app (rather than tokens) which should offer great granularity in permission requests, but we are currently blocked because of a bunch of technical limitations. So until those get unblocked there isn't much that can be done unfortunately :cry:

@jasonwilliams Try the steps here: https://github.com/eamodio/vscode-gitlens/issues/1208#issuecomment-739052899 but again your PAT would have to have the `repo` scope for things to work.

**Comment by jasonwilliams** [comment]
> Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.
> 
> You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
> 
> I've reworked the notifications a bit to be clearer and added a "don't ask me again" type option. Unfortunately there still is 1 extra notification in certain cases, but that is because of [microsoft/vscode#111529](https://github.com/microsoft/vscode/issues/111529). So once that gets fixed I can remove it.

Is this still only on insiders?
or on Stable too? I don't see a "don't ask me again" option on stable so was just wondering

**Comment by pcgeek86** [comment]
> Ah, so you want an always reject? Curiously, why don't you want it to connect to GitHub?

Why *would* I want to connect to GitHub? I can, and have been, using GitLens *without* connecting to GitHub. The constant prompt is irritating.

**Comment by mikeyhew** [comment]
Is there a way to connect to GitHub after opting out?

**Comment by eamodio** [comment]
> Why would I want to connect to GitHub?

@pcgeek86 Because of the features the integration enables. I'm glad that you are happy with what you have, but there are plenty of people that want/would benefit from a deeper integration with GitHub.

And I 100% agree that the constant prompt is totally aggravating, and I apologize for that (I switched from my own auth to using the vscode auth right before I shipped GitLens 11, and I really needed to do more scenario testing because of those changes). You can use the insiders edition today to get the fix for this, and I will be releasing it to stable very soon.

@mikeyhew You can click the _Connect to GitHub..._ link in the hovers, or click on the _Connect_ command for the remote in the _Remotes_ view.
