### ISSUE TITLE
Blame information Bug

### ISSUE THREAD

**Issue by lh123** [eamodio/vscode-gitlens#122]
When I only delete a few lines in the file, but Blame information is not updated
**Before deleting**
![image](https://user-images.githubusercontent.com/10697249/28492469-2bf2bbd2-6f37-11e7-915c-cc51799acc79.png)
**Afte rdeleting**
![image](https://user-images.githubusercontent.com/10697249/28492475-43f87848-6f37-11e7-82ad-0eddc513f685.png)

**Comment by eamodio** [comment]
This seems to only happen with deletes -- I'll dig into this more.

**Comment by eamodio** [comment]
@lh123 I've dug more into this and unfortunately `git blame` doesn't provide any information to know if a file has been edited with only deleted lines. Kind of feels like a git bug to me, but who knows. `git blame` does return proper information if there was any updated or added line in the file.

Because of the current `git blame` behavior and GitLens' reliance on `git blame` there isn't anything I can reasonably do here. Sadly, given that I'm going to close this issue as *won't fix*.

Although if `git blame` starts returning proper blame information for a file with only deletes then GitLens would just start working.
