### ISSUE TITLE
Git diff should show the git hunk instead of the one line

### ISSUE THREAD

**Issue by cdloh** [eamodio/vscode-gitlens#124]
- GitLens Version: 4.3.3
- VSCode Version: 1.14.2
- OS Version: Win10

Steps to Reproduce:

1. Make changes to a file and save
2. Go to line and however over line to show diff

If possible it'd be great to show the hunk instead of just that single line.

**Comment by eamodio** [comment]
@cdloh I'm somewhat concerned about the UX/UI of something like this. When I originally added the "diff" feature I did try out showing the whole chunk, but it made the hover much larger and because I don't have enough control of the coloring and formatting of the hover (as far as I know) I can't make it really look like a diff.

Do you have any thoughts on this and any more color to add to why you'd really want this feature?

**Comment by eamodio** [comment]
@cdloh or anyone else who might want something like this -- thoughts on the above?

**Comment by ro-savage** [comment]
Yes @eamodio, would love this feature! Would be icing on the cake for your plugin.

Have a look how webstorm / intelli-j handle it.

![webstorm-example](https://user-images.githubusercontent.com/9244507/30350051-872ae746-9858-11e7-9098-405efa42b8db.gif)

You show the entire 'hunk', that is all the adjoining lines, and only show the *old* code not a proper diff. You don't need to see a diff, because you can already see what the current code does.

Bonus is adding options to restore old code, copy old code, or view in a proper diff screen.

If you haven't tried out Jetbrain's product and how they handle git, I'd highly recommend it. It's by far the most polished of all IDEs.

There's an issue in vscode (Microsoft/vscode#10782) to add similar functionality but looks like it is dead.

**Comment by eamodio** [comment]
@ro-savage Hehe - just replied on that thread. I was thinking that this issue might be somewhat related, but not entirely the same -- since I read more into the other issue about being able to stage/unstage/revert lines in a diff.

As I mentioned in the other issue, I'm not sure there is a good UI metaphor available to extensions right now for this -- since I think I'd be even more against using code actions for something like this (I think).

Providing actions on the current `changes` hover to revert the line -- is something that should be doable. Although dealing with multi-line chunks gets a little challenging I think, because I'm not sure if the current hover style UI is right for that -- have to think on it more.

But to provide something like I think you are after isn't within the spirit of the current hovers I utilize today. They are quite limited, as deleted blocks aren't accessible, chunks are truly visible, etc. There are probably ways around a lot of this, but would require more thinking through the available UI options and the desired ux/behavior.

**Comment by ro-savage** [comment]
I don't believe it requires code actions to the lightbulb.

Simply hover over the gutter or line (depending on settings) and it shows the same pop-up but instead of a 
```
+ sometext
- sometext
```

you would see the whole chunk such as

```
sometext that i
delete or changed
from before
over multiple lines
```

underneath that would appear actions buttons
Revert | Copy | Commit | Diff

Revert: Replaces your changes unstaged changes with the original code
Copy: Copies the original code
Commit: Commits only that chunk of code - additional dialogs as per usual commits
Diff: Shows the hunk diff in the regular diff viewer

Do you think it's something you'd like added to gitlens and that gitlens is already setup for being able to get that data / provide that actions?

Or would you prefer it be left to another plugin/core to handle?

**Comment by donaldpipowitch** [comment]
> since I read more into the other issue about being able to stage/unstage/revert lines in a diff.

I'd love to have "revert" button in the hover diff 😍

**Comment by eamodio** [comment]
Given the new built-in functionality in vscode itself: https://github.com/Microsoft/vscode/issues/10782, can I close this? Or is there something beyond what vscode provides that GitLens should?

**Comment by ro-savage** [comment]
@eamodio - I think this is safe to be closed. Thanks for looking into i :)

**Comment by eamodio** [comment]
I'm going to close this then -- if you feel differently please let me know and we can re-open
