### ISSUE TITLE
Hovers are not working when scrollable current line blame annotations are disabled

### ISSUE THREAD

**Issue by Nick-SHM** [eamodio/vscode-gitlens#1293]
- GitLens Version: 11.1.0
- Git Version: 2.29.2
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Set `gitlens.currentLine.scrollable` to `false`.
2. Hover the cursor over a current line blame annotation.

Expected behavior (when `gitlens.currentLine.scrollable` is set to `true`):

<img width="1680" alt="expected" src="https://user-images.githubusercontent.com/10667496/103156375-f09e0180-47e2-11eb-8488-ba96609bf971.png">

However, hovers are not working if `gitlens.currentLine.scrollable` is set to `false`:

<img width="1680" alt="observed" src="https://user-images.githubusercontent.com/10667496/103156377-f4318880-47e2-11eb-8fdd-a9e244953484.png">

**Comment by eamodio** [comment]
Unfortunately, this is expected behavior (because of limitations with the VS Code APIs). Setting `gitlens.currentLine.scrollable` to `false` only allows the hover to show at the very last character of the line (not very useful, I know). But you can also set `"gitlens.hovers.currentline.over": "line"` and that will allow the hovers to show anywhere over the line.

I've added a note about this to both the setting and the GitLens settings UI.
