### ISSUE TITLE
Welcome screen on every editor window is very tedious

### ISSUE THREAD

**Issue by jlaxson** [eamodio/vscode-gitlens#1302]
I just discovered Gitlens and find the functionality useful, thank you to all who contribute.

I have about a dozen editor windows open, and the install process added a Gitlens welcome tab to each and every one of them.  Combined with the snowflake effect, all of the sudden VScode was consuming 300-400% cpu and my fan was raging, as soon as I hunted them all down everything was back to fine.  The welcome note content is great (although putting it on _all_ the windows is a bit much, don't know how much control you have on that).  But overall it was a bit of a sour first-use experience, just wanted to provide that feedback.

**Comment by eamodio** [comment]
@jlaxson 

First sorry about that -- definitely not an ideal (nor desired) first experience 😢 

Just to be clear when you say editor windows open -- you mean new vscode windows, right? 

Unfortunately, I don't really have good control over that, since it seems like a timing issue -- where each window checks to see if this is a "first-install" and if so shows the welcome experience.

I'll have to think about this some more.

Maybe I could only show the welcome experience if the window is focused (I actually have access to that state, and event when it changes), and only on the first focused one.

**Comment by eamodio** [comment]
I've changed it so the welcome experience & what's new notification to only show on the first focused window after install.

**Comment by eamodio** [comment]
@jlaxson Thanks so much for the report -- I never even thought about anything like this.

**Comment by jlaxson** [comment]
@eamodio Thanks a lot, glad I could be helpful and there was a workable fix.  Vscode windows are to me what chrome tabs are to some others, so can see that I might be a bit of an extreme case.  Cheers!
