### ISSUE TITLE
Gitlens sidebar icon differs when opening vscode with a workspace

### ISSUE THREAD

**Issue by mentofa123** [eamodio/vscode-gitlens#1319]
- GitLens Version: 11.1.3
- Git Version: 2.29.2.windows.3

- VSCode Version: 1.52.1
- OS Version: Windows 10 19042.685

Steps to Reproduce:

1. Open vscode without opening a workspace.
2. Open a workspace. This should be the sidebar icon now: ![image](https://user-images.githubusercontent.com/15869016/104298859-c461d080-54c4-11eb-808e-08fc290c427b.png)
3. Close vscode and reopen it so it loads the last workspace. The icon now looks like this: ![image](https://user-images.githubusercontent.com/15869016/104299050-01c65e00-54c5-11eb-8786-6627574be594.png)

I searched through the existing issues and could not find any related issue like this. Is this a bug or is this intended?

**Comment by LeonardoKojimaCMD** [comment]
I'm having the exact same problem

I realized that ![image](https://user-images.githubusercontent.com/15869016/104299050-01c65e00-54c5-11eb-8786-6627574be594.png) is the commit icon

If you drag the commit tab to the side bar, the commit icon should appear in it
![image](https://user-images.githubusercontent.com/74206877/105221286-a9800380-5b37-11eb-9c70-01ec7800f323.png)

The same applies to the other tabs. Each one of them has its own icon

A temporary solution to this is closing the workspace (`Ctrl + K` `F`) and reopening the repository folder

**Comment by eamodio** [comment]
@mentofa123 Did you drag the views around? If so then this is somewhat expected behavior -- since as @LeonardoKojimaCMD says, each view has its own icon, so if you drag them into their own "group" on the activity bar they are unique.

In VS Code you can right-click on the activity bar icon (or the view header itself) and select _Reset Location_ which will reset that view back to its original location. Although if you just want to switch to (or between) having all the GitLens views under the SCM activity or under a GitLens activity, you can use the `GitLens: Set Views Layout` and then choose the layout you want.

**Comment by mentofa123** [comment]
It's not the commit tab dragged to the sidebar. My view is the view you set with GitLens: Set Views Layout 
I know that i could drag any any view to the activity bar but my problem was that the icon of the complete gitlens view changes to the commit icon after reopening vscode with the last opened workspace

**Comment by LeonardoKojimaCMD** [comment]
Once you set `GitLens: Set Views Layout` to `GitLens Layout` for the first time, the original Gitlens icon should appear in the side bar.
As @mentofa123 said, if you then close and reopen VSCode, it will reopen the last used workspace. In this case, the Commit icon appears instead of the Gitlens icon **because** it is the first tab in GitLens Layout. If you change the order of the tabs, VSCode will then reopen with the first tab icon.
A quick way to make the original Gitlens icon appear is closing the workspace (`Ctrl + K` `F`) and reopening the repository folder. Then again, this is not the ideal solution, but a temporary one.

I apologize for causing confusion earlier.

**Comment by mentofa123** [comment]
"Problem" is gone since the last update.
