### ISSUE TITLE
Stashes created with command line don't show up in the "Stashes" section

### ISSUE THREAD

**Issue by foreignmeloman** [eamodio/vscode-gitlens#1332]
As the title says. Even after hitting the refresh button of the "Stashes" section, the new stash doesn't appear.

- GitLens Version: 11.1.3
- Git Version: 2.30.0

- VSCode Version: 1.52.1 (system setup)
- Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- Date: 2020-12-16T16:34:46.910Z
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create stash in the terminal window with git stash push command
2. Refresh "Stashes" pane of GitLens

**Comment by eamodio** [comment]
I'm guessing this is caused by GitLens not being able to watch for repository changes. Typically this is because the repository root is outside the folder/workspace opened in VS Code (there is a VS Code issue tracking this).

If you enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. You can check in the *GitLens* channel in the *Output* pane to see if you see a log line that looks like `Repository[<path-here>] doesn't support file watching;`

If so, that explains the view not auto-refreshing. In tomorrow's Insiders edition, I have added watching in more cases to workaround the VS Code issue, and clear indicators if watching is unavailable.

Although, I am concerned that the refresh button didn't work (I can't reproduce that even when file watching isn't available).

Can you capture the logs for when you press the refresh button?

**Comment by foreignmeloman** [comment]
> I'm guessing this is caused by GitLens not being able to watch for repository changes. Typically this is because the repository root is outside the folder/workspace opened in VS Code (there is a VS Code issue tracking this).

In my case the repository root is the same as opened project folder. The project has too many files to track and I get this message from VSCode on startup. I usually don't mind the autoupdate part and refresh Explorer and Source Control manually, but doing the same for GitLens panes doesn't work. Now I remember that new tags created in terminal also don't appear.
![image](https://user-images.githubusercontent.com/11769352/105019603-b6312880-5a5f-11eb-9b34-7352e71e526c.png)

FYI I'm using Remote SSH connection, so the execution is not local.

Here is a screencap of the issue itself:
![gitlens](https://user-images.githubusercontent.com/11769352/105029137-5e002380-5a6b-11eb-9c8d-cb3a1a3c2785.gif)
And the recorded log: [gitlens_log.txt](https://github.com/eamodio/vscode-gitlens/files/5835553/gitlens_log.txt)

Hope this gives you some hints!

**Comment by eamodio** [comment]
@foreignmeloman Thanks for the extra information -- it definitely helped. 😄 

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by foreignmeloman** [comment]
@eamodio Thanks for the quick response!

Unfortunately I see the same issue in the insiders version 2021.1.1904 :(
![gitlens_insiders](https://user-images.githubusercontent.com/11769352/105149880-792b6b80-5b1d-11eb-9706-e130f4977e37.gif)

And here is the log: [gitlens_log2.txt](https://github.com/eamodio/vscode-gitlens/files/5841152/gitlens_log2.txt)

**Comment by eamodio** [comment]
@foreignmeloman Ah, the issue is that you have the previous insiders build, it needs to be `v2021.1.2004` or later.

**Comment by foreignmeloman** [comment]
It works now, thanks!
