### ISSUE TITLE
Need to allow GitLens to connect to GitHub in every Codespace

### ISSUE THREAD

**Issue by egamma** [eamodio/vscode-gitlens#1336]
GitLens shows the following dialog whenever I open a new Codespace:

![image](https://user-images.githubusercontent.com/172399/105146729-9998fd00-5b00-11eb-9f82-240b6e1c2b89.png)

Suggest to use the new API `context.globalState.setKeysForSync` so that my choice is remembered across different Codespaces.

The follow-up problem is when I select "Allow" in the dialog, then I have to do a auth flow in GitHub, but I'm already logged into GitHub.

**Comment by corwin-of-amber** [comment]
If I just want the plain git history functionality, and click "Deny Everywhere", then I still have a nagging notification in the accounts icon on the bottom left. 😢 
<img width="346" alt="Screen Shot 2021-01-21 at 0 56 56" src="https://user-images.githubusercontent.com/704372/105251112-92ff9980-5b83-11eb-8178-82c1190893b5.png">

**Comment by eamodio** [comment]
@egamma So there is a bunch of back-story to why that notification exists. But the TLDR version is I'm blocked by https://github.com/microsoft/vscode/issues/111529

Today the VS Code authentication api provide a `authentication.getSession(<id>, <scopes>, { createIfNone: false })` that allows an extension to get an existing session if one exists. This works great for the case when there is no matching (scopes) authentication session -- e.g. it is silent. BUT if there is a matching authentication session, AND the extension hasn't be granted access to it -- then VS Code pops up a dialog like this:

![image](https://user-images.githubusercontent.com/641685/105294043-428a3b00-5b87-11eb-9038-1733b3cb7bb5.png)

This creates a big issue for extensions, because we have no way to silently know if we have an authorized session or not. So because GitLens tries to figure out if it has an authorized session to provide passive features (i.e. features that the user doesn't take an explicit action to invoke), and because that prompt is not at all friendly to the user if they didn't do anything to cause it, I added an explanatory notification to tell the user what will happen and why, and offer a way to completely opt-out.

So until https://github.com/microsoft/vscode/issues/111529 is fixed/addressed I don't think there is really much I can do. You can disable the integration completely, by setting `"gitlens.integrations.enabled": false` in your settings. And I am currently syncing the `Deny Everywhere` choice, but I was/am very hesitant to sync the `Allow` choice to other machines, because I might want to allow it on my home machine, but not on my work machine, etc. Although I guess I could add an `Allow Everywhere` button if you want to opt-into that.

Also as for:
>The follow-up problem is when I select "Allow" in the dialog, then I have to do a auth flow in GitHub, but I'm already logged into GitHub.

That is also completely controlled by VS Code

And @corwin-of-amber your issue is also out of my hands and is fully controlled by VS Code.

**Comment by egamma** [comment]
@eamodio thanks for the background!

**Comment by jrieken** [comment]
> This creates a big issue for extensions, because we have no way to silently know if we have an authorized session or not

@eamodio Are you saying that you want silent access to a session or silent knowing that a session would exist if you would be asking for it?

> prompt is not at all friendly to the user if they didn't do anything to cause it, I added an explanatory notification to tell the user what will happen and why

Instead of silent access and custom notifications wouldn't it be better to provide a reason for why you want to get a session? That would allow to make a UI more friendly/informative and wouldn't rely on notification popping up. With GH issue notebooks I have the same challenge: it works well except for thinks like `author: @me` or quota restriction. I would also like to explain that to users, but not with custom UX

**Comment by eamodio** [comment]
@jrieken 

> Are you saying that you want silent access to a session or silent knowing that a session would exist if you would be asking for it?

To me that are kind of one and the same. I want/need to be able to get access to a session that I've been previously granted access without prompting the user if there isn't one.

> Instead of silent access and custom notifications wouldn't it be better to provide a reason for why you want to get a session?

Having a reason (and possibly a more global opt-out) on our prompts would be very nice, but I don't think that helps address my silent access concern. In GitLens, I want to use the access if I have been granted it, passively (for avatar lookups, pr & issue linking details, etc) but I don't want to prompt/bother the user UNLESS they take a specific action (or actions) to opt-in to wanting to connect to GitHub to provide those features.

/cc @RMacfarlane

**Comment by jrieken** [comment]
> I want/need to be able to get access to a session that I've been previously granted 

"I" as the user or the extension?

**Comment by eamodio** [comment]
Extension

**Comment by eamodio** [comment]
Can you please verify this fix in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
