### ISSUE TITLE
Multiline constructor displays multiple code lens

### ISSUE THREAD

**Issue by MonsieurMan** [eamodio/vscode-gitlens#134]
- GitLens Version: 4.4.1
- VSCode Version: 1.15.1
- OS Version: Fedora 26

With my colleagues, we like to split constructor parameters into multiple lines but it ends up displaying multiple git code lens with this extension : 
![constructor](https://user-images.githubusercontent.com/13108166/29762647-e2e82958-8bcf-11e7-9f49-362cb3d3e527.png)
Is this expected behavior or are we lonely to split constructor parameters?

**Comment by eamodio** [comment]
Hrm -- I'll look into what is going on here.

**Comment by eamodio** [comment]
@MonsieurMan sorry for the delay on this. This is expected behavior depending on how `gitlens.codeLens.locations` and/or `gitlens.codeLens.customLocationSymbols` is set. If you include `blocks` in `gitlens.codeLens.locations` or `property` in `gitlens.codeLens.customLocationSymbols`, then these code lens will show, because the Typescript language server (correctly) reports those line as properties.
