### ISSUE TITLE
[feature request] Show a list of files changed for current branch (ignoring merges)

### ISSUE THREAD

**Issue by sschwartz0** [eamodio/vscode-gitlens#139]
First off - thank you for creating and actively maintaining this amazing extension. I discovered it yesterday while trying to convince my team to get off PHPStorm. The only thing stopping our chief guy from switching over is being able to see what files were changed on a branch in the file explorer.

The new gitlens explorer is so close to solving this problem for him and many others (there's a two year old thread about this on vscode issues with thousands of requests).

Would it be possible to add an option for the Gitlens Explorer -> Current Branch where we can see a straight list of files modified, created or deleted for just that branch while also ignoring changes from any merges? This would be without nesting changes within commits.

I've never requested a feature on anything before so just want to reiterate that you are the man.

**Comment by eamodio** [comment]
@sschwartz0 Thank you so much for your kind words -- really appreciate them. When you say a list of files modified/created/deleted on that branch -- I don't think I'm really understanding. Like in comparison to another branch or the working tree? Or literally a full file explorer with a deduped list of files changed in all commits since the start of that branch?

If its the latter, what is the use-case for that? (Not even sure how hard something like that would be). If its the former -- I am definitely thinking about being able to select branches/commits to compare with one another (including the working tree).

If there is another tool that provides this can you post a screenshot of what you would like too?

Thanks again!

**Comment by sschwartz0** [comment]
So this image is from PHPStorm. They indicate changes in the full file explorer by coloring the filename. Green is newfile, blue is edited file. Grey is deleted (forgot how to get that to show without the file disappearing...)

![image](https://user-images.githubusercontent.com/21964998/30398215-7151ce40-9884-11e7-83c1-b14095a5559d.png)

Based on the vscode issue thread it sounds like editing the current file explorer is near impossible. I guess the solution would be either making a new file explorer, which sounds daunting, or adding to the new gitlens explorer a "Current changes" dropdown (with the option to auto open) that shows the changed files from the branch you originally checked out from. So when you go back to that branch after a day or two you can easily find the files you were working on. Cool options would be showing:

1. Since your last commit
2. Since the branch checkout (all commits but not including changes from merges)

Hope this made sense

**Comment by eamodio** [comment]
Thanks for the extra information and color. So yeah, currently not possible to affect the file tree. But on the others I have some questions still.

> 1. Since your last commit

Isn't that handled by the current SCM view? It shows all the files changed that haven't yet been committed.

> 2. Since you opened the editor/branch and started working again

I'm not sure I really understand this one -- so you would want changes from the most recent commit when you open vscode? What is the use-case here? I'm trying to understand the workflow that would make this type of information useful.

> 3. Since the branch checkout (all commits but not including changes from merges)

So this is kind of like what the new GitLens view already does in the `Repository Status` node -- it shows all the commits waiting to be pulled down and/or waiting to be pushed up. But they are organized by commits, rather than just a file list. So if there was a way to just show things as a straight (flat) file list would that get at what you are asking?

Sorry for all the questions -- I just want to have a **really** good idea of a use-case and workflow before I add features to GitLens :)

**Comment by sschwartz0** [comment]
Ahhh - so on PHPStorm it makes the color changes in the file explorer as you are actively editing the codebase. So it would be nice to have a straight list of changed files without having to dig through the trees/commits.

For #2 it would be empty when you switch branches or reopen your editor and would start adding files to the list as you modify them. (there is open editors but sometimes I don't want tons of tabs open).

For #3 if for example I'm working for over a week on a feature it'd be awesome to see what files I changed since the start of that branch

Hopefully this makes sense. I can make an image representation tomorrow or friday of what I mean.

**Comment by eamodio** [comment]
OK looking forward to it.

For 1 -- Currently you can right-click and choose `Open File` to get at the file, rather than the diff -- it also works if you select multiple files in 1.16. GitLens also adds a `Open Changed Files` command if you right-click on the `Changes` or `Staged Changes` headers

For 2 -- I still don't understand why the SCM view doesn't already handle that?

For 3 -- I definitely get the desire here, I just don't know if there is a reasonable way to get the point at which a branch came from. So comparing 2 branches would be fine, because it could find the common ancestor, but just having the branch you are on, I don't think there is a way to know that this branch `foo` started from another branch called `bar`, so I wouldn't have a way to match it to anything to tell the differences. Now for a branch that is tracked to a remote, that is different -- which GitLens does today, just organized by commit

**Comment by sschwartz0** [comment]
I guess 1 and 2 are more of a UX thing but I did not know about the right click options so thank you for that! For me 1 and 2 are closed, my boss can live in PHPStorm if he wants ;)

For 3 I think that an option to also show the list of files by itself (without having to go commit by commit) would be great. I was thinking of a branch tracked to remote - for instance a development, staging or master branch (whatever your organization uses) - I just didn't know it heh.

**Comment by eamodio** [comment]
@sschwartz0 the latest [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.1.1-beta) attempts to address this by adding a new `Changed Files` node to the repository status in the custom view. FYI, you need to set `"gitlens.insiders": true` in order for it to show up.

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know what you think and/or if you experience any issues -- thanks!

**Comment by sschwartz0** [comment]
@eamodio This is great! Sorry I never got you a picture but this is awesome. Is it possible to have gitlens autorefresh when you have no changed files and then there is the first file change? Other then that, love it.

Also another cool feature would be to also show a list of all changed files (from the master branch) since the branch was created. So there'd be two dropdowns:
Changed Files Since Last Push
All Changed Files

**Comment by eamodio** [comment]
@sschwartz0 the latest [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.2.0-beta) polishes up this a bit more -- but no auto-refreshing yet

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know what you think and/or if you experience any issues -- thanks!

**Comment by borekb** [comment]
Hi, the way I understand the feature request, and what would be very useful to me as well, is a way to compare the current state in my `feature-branch` to the base branch (`master` most commonly). **GitHub's pull requests** / compare view are a great example of this:

![image](https://user-images.githubusercontent.com/101152/30636277-437b6668-9df5-11e7-8b1d-f1eb951b318f.png)

Admittedly, it won't be very simple to provide this in the limited UI that GitLens has but for me as a developer, this overview is perfect. Currently, I do something like this as a workaround:

First, I manually find which commit is the first not in my branch (can be determined by `git merge-base --fork-point master`):

![image](https://user-images.githubusercontent.com/101152/30636471-d4286c74-9df5-11e7-95ff-cf1900d9c390.png)

Then I do directory compare using an external app:

![image](https://user-images.githubusercontent.com/101152/30636506-f4d18d34-9df5-11e7-97ac-5422e304d651.png)

It would be a dream come true for me if I could do the whole workflow in a smoother way inside VSCode thanks to GitLens :) 5.2 beta seems to implement a compare between local branch and its remote tracking branch, e.g., `feature-branch` vs. `origin/feature-branch`.

**Comment by eamodio** [comment]
@borekb I'm definitely thinking about providing something along those lines. :)

**Comment by sschwartz0** [comment]
Thanks @borekb for helping me out here. I've only been working as a dev since March so still working on my technical communication for devtools heh..

@eamodio Again, you're awesome for how hard you work on this. Any beer money donation link?

**Comment by eamodio** [comment]
@sschwartz0 thank you for you very kind words. I hadn't really thought about setting up a donation link or anything -- maybe I'll look into that! Thanks again!

**Comment by sschwartz0** [comment]
So I found an extension that does the base branch comparison so not sure if you want to keep working on this or not. Works well and clicking on a file opens the SCM file view. However it's only got a 1000ish downloads so not sure what the support is like for it. It's nice to see both change histories (latest commit changes from GitLens and full base branch changes from this one.

It's called Git Tree Compare
![image](https://user-images.githubusercontent.com/21964998/30767411-3d899e24-9fb1-11e7-9f59-f5798487a241.png)

**Comment by borekb** [comment]
@sschwartz0 that's very nice indeed! Thanks for the tip. Feels like a natural fit for GitLens in the future 😉

**Comment by eamodio** [comment]
@sschwartz0 @borekb 
Let's track further conversation/request on this here: https://github.com/eamodio/vscode-gitlens/issues/115

Since GitLens 5.2 I *think* addresses the main concern and the rest imo is about branch comparing

**Comment by eamodio** [comment]
@sschwartz0 Since you asked about donation, etc -- one thing that is always very helpful to extensions you love is reviews on the marketplace. So if you haven't left one yet, I'd encourage you to do so ;) Thanks in advance.
