### ISSUE TITLE
Tick the line to display the avatar button, but the avatar is not displayed

### ISSUE THREAD

**Issue by LongYue9608** [eamodio/vscode-gitlens#1401]
- GitLens Version:11.2.1
- Git Version: git version 2.27.0.windows.1

- VSCode Version: 1.53.2
- OS Version:

Steps to Reproduce:
Tick the line to display the avatar button, but the avatar is not displayed. I had it before. I don't know why it suddenly disappeared. I tried to uninstall and reload it, and install other versions, but it still doesn't display

**Comment by LongYue9608** [comment]
![avatar](https://user-images.githubusercontent.com/25579482/109283487-d1ab0280-7859-11eb-9134-6cb3da840f25.gif)

**Comment by eamodio** [comment]
Is your avatar the only one that doesn't show up, or does it affect others as well? Is this repo on GitHub? If so, did you allow GitLens access to GitHub?

**Comment by LongYue9608** [comment]
I don't know what happened. Before, the avatar can be displayed. Plug-in functions can be used, but the avatar is not displayed. It's very uncomfortable @eamodio

**Comment by eamodio** [comment]
If you visit https://www.gravatar.com/avatar/00000000000000000000000000000000.jpg?s=16&d=robohash do you see a small avatar?

Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

I've also added a new _GitLens: Reset Avatar Cache_ command that can be run from the command palette to hopefully reset any bogus image that might have been cached.

**Comment by ttian226** [comment]
由于总所周知的原因，https://gravatar.com/这个网址应该打不开了，过一段时间应该就可以了，或者找个梯子。

**Comment by LongYue9608** [comment]
@eamodio Thank you. Run gitlens: reset avatar cache. My problem has been solved
