### ISSUE TITLE
Element with id is already registered

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#1405]
I am also getting this error with v1.53.2 of VSCode and v11.2.1 of GitLens. It started recently and appears periodically.
<img width="462" alt="Screen Shot 2021-02-23 at 11 44 55 PM" src="https://user-images.githubusercontent.com/5005914/108965038-27509680-7631-11eb-9251-b5b681486955.png">

_Originally posted by @njbbaer in https://github.com/eamodio/vscode-gitlens/issues/606#issuecomment-784868320_

**Comment by eamodio** [comment]
@njbbaer Can you provide details on when/how you are experiencing it? And is it always with tags?

**Comment by njbbaer** [comment]
@eamodio I noticed that message in VSCode randomly every hour or so for a few days, but it hasn't recurred recently. I don't recall if it always had a tag or not. I'll post back here if it starts happening again.

**Comment by peacefulhill** [comment]
In VsCode 1.53.2 I get the following error since upgrading everytime I push or pull:
gitlens:repository(c:/folder/repository):compare-branch(master):root is already registered

**Comment by welcometochristown** [comment]
I get this message when I swap branches from the command line then switch back to visual studio code.

**Comment by eamodio** [comment]
@welcometochristown You get this every time? Or at least reasonably reproducible?

**Comment by iomarcovalente** [comment]
This was occurring to me too - closing and opening VS Code fixed it, but cannot pin-point what triggered it in first place. Luckily it was nothing harmful but I got scared for a second that my local git repo was corrupted or something 😅

**Comment by welcometochristown** [comment]
I can't seem to reproduce it. I have no idea what is causing it. Sometimes it happens when I commit, sometimes when I push and sometimes just randomly when there is a change.
The only thing I thought it might be is that I have 4 different repos in my workspace but I can't confirm that's the reason.

Closing visual studio does fix it temporarily but always comes back.

**Comment by welcometochristown** [comment]
@eamodio Actually I think I can reproduce it by clicking away from the Source Control tab and then back to the Source Control tab in vs code.

**Comment by davideamato** [comment]
I also got this on vscode 1.56 on macOS 11.2.3. I had a workspace open with two git repos, and the error appeared when opening the GitLens tab. It kept reappearing while I was committing some changes, which I managed to do successfully.

<img width="448" alt="Screenshot 2021-05-10 at 17 32 16" src="https://user-images.githubusercontent.com/50680451/117693550-0d493d80-b1b6-11eb-8d05-7630420f3c5b.png">

**Comment by eamodio** [comment]
I believe this has been resolved in the latest GitLens insiders edition (should be coming to GitLens stable soon).

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by hans2520** [comment]
It happens for me a lot when I am in a workspace with many repos open, and I am in the gitlens view and one of the historical dropdowns in the left sidebar is expanded (e.g. Commits, Repositories, File History, etc.)

Which repo it happens to appears to be random, but once it happens, it keeps happening repeatedly until I right click the repo in that historical dropdown, and click "Close Repository". Then the errors stop appearing -- for now. Since I work in remote environment that gets disconnected every 9 hours, it's liable to pop up again after reloading the environment entirely in order to re-connect (another thing that's annoying about VS Code... it can't reconnect without re-loading the entire workspace).

Because of the random nature of the repo it happens to, this makes me think that there is some parallel processing going on and that it literally is trying to "register" something twice that it already has registered once, and will keep doing so until you close it. 

Using GitLens 114.4.1 on VS Code 1.55.1

**Comment by louking** [comment]
also seeing the following, with https://github.com/louking/rrwebapp, https://github.com/louking/loutilities, https://github.com/louking/running open in workspace (in that order), vscode 1.57, GitLens 11.4.1

Element with id gitlens:repository(c:/folder/repo):compare-branch(master):root is already registered
