### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by akhilreddy619** [eamodio/vscode-gitlens#1509]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `11.4.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 159,
		"activateCallTime": 2,
		"activateResolvedTime": 264,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "eamodio.gitlens",
				"_lower": "eamodio.gitlens"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": []
}
```

Showing unresponsive as status. Not able to use Git features at all because of this.

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?

Also, if this issue is reproducible, can you please enable output channel logging by running from _GitLens: Enable Debug Logging_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from the both _GitLens_ and _GitLens (Git)_ channels.
