### ISSUE TITLE
"Don't show again" on debug log warning doesn't work

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#1548]
- Enable debug logging
- Use gitlens for awhile
- Get this notification
![image](https://user-images.githubusercontent.com/323878/122134874-51061700-cdf4-11eb-8b50-a9a5ba4deb94.png)
- Click "Don't show again"
- But I know I've seen this multiple times. 

Actually maybe it's just saved per-workspace?

**Comment by eamodio** [comment]
It's saved in user settings:
```json
"gitlens.advanced.messages": {
	"suppressDebugLoggingWarning": true
},
```

I'm not sure how that would fail -- maybe settings sync?

**Comment by roblourens** [comment]
I don't have that setting but I'll check for it next time

**Comment by roblourens** [comment]
When I click "Don't show again", it doesn't add the setting

**Comment by eamodio** [comment]
@roblourens are you aware of a settings change where we are returning a proxy object rather than a normal object? That is what causes this issue -- at some point VS Code stopped returning an object from a `WorkspaceConfiguration.get` call and instead returns a proxy object.

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by roblourens** [comment]
cc @sandy081

**Comment by sandy081** [comment]
Yes the API returns proxy mainly for perf reasons - so that we do not clone the complete settings tree when we give it to the extension.

**Comment by eamodio** [comment]
@sandy081 when did that change? Because that is a breaking change depending on how the object was used.

**Comment by sandy081** [comment]
3 yrs ago - https://github.com/microsoft/vscode/issues/39576
