### ISSUE TITLE
the code moves by activating git lens

### ISSUE THREAD

**Issue by kianxineki** [eamodio/vscode-gitlens#179]
When changing files the code moves, it also happens when you switch between files.

Is it possible to reserve that space until the text appears to avoid this effect?

- GitLens Version: 5.7.1
- VSCode Version:
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- OS Version:
Linux T460 4.10.0-37-generic # 41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
https://www.youtube.com/watch?v=Ll7m4TvGqdA

**Comment by eamodio** [comment]
@kianxineki When you say the code moves -- do you mean the code lens pushing the lines around?

I tried to look at the video, but it says it in unavailable :(

**Comment by kianxineki** [comment]
@eamodio yes

Video fixed :)

**Comment by eamodio** [comment]
@kianxineki unfortunately that is just how vscode deals with code lens. You can turn off the GitLens code lens feature by default by setting `"gitlens.codeLens.enabled": false`

**Comment by kianxineki** [comment]
@eamodio I caught the attention when it happened to me, but I understand what he says. Do you know if it is in the vscode roadmap?

I will use that configuration until they solve it, very useful :)
Thanks for everything!

**Comment by eamodio** [comment]
I'm not sure which part you have an issue with? The fact that code lens pop in or that each time you switch to a new tab they pop in all over again? I can't see anything really changing with the former because you don't want to delay the opening of a file to know where code lens will be rendered, but the latter I could see by them keeping a cache of the most recent opened files so that code lens doesn't need to be full re-evaluated.

I would encourage you to open an issue on the vscode github repo with what you'd like to see.
