### ISSUE TITLE
Seems that gitlens doesn't annotate merge conflicts correctly

### ISSUE THREAD

**Issue by JasonKleban** [eamodio/vscode-gitlens#187]
Whenever I have a merge conflict to resolve, I am trying to use gitlens v5.7.1 to tell me who changed what more recently on which branch - vscode enhances the raw merge conflict text with coloring and options to take the incoming change or keep the current change, etc.  But gitlens seems to show the same history for both sections.  Can that be fixed?

Thanks!

**Comment by eamodio** [comment]
@JasonKleban can you provide a screenshot of the issue, I'm not sure I 100% understand

**Comment by JasonKleban** [comment]
Also, once merged, the annotations on the _staged_ change show the wrong history.  For example, on a branch that only diverged just a few days ago, the staged change of the merge back to master shows "Joel, 7 months ago * ..." from a seemingly random old commit, rather than the real diverging commit of 17 hours ago.

**Comment by eamodio** [comment]
I don't think there is really much I can do with the first issue, because the `git blame` command (which GitLens uses, doesn't provide any real information about those conflicted lines. But the 2nd issue about diff with the staged version, I am working on in another branch (as it requires quite a lot of plumbing) -- when that lands it should hopefully address this.

Would you mind opening a separate issue for the diff with staged issue?

**Comment by eamodio** [comment]
Closing this out, since there isn't much I can do for the original issue
