### ISSUE TITLE
Nested .gitignore files can cause blame to fail with a repo within another repo

### ISSUE THREAD

**Issue by krzysztof-balas** [eamodio/vscode-gitlens#20]
Hi,
plugin seems not to be working if the repository is cloned inside another cloned repository.
VS Code works fine in that case

**Comment by eamodio** [comment]
@krzysztof-balas can you provide more details? Can you add `gitlens.advanced.output = 'verbose'` to your settings and then take a look at the Output pane for GitLens?

**Comment by krzysztof-balas** [comment]
Thanks and sorry for the delay. I recognized the thing thanks to "verbose" log.
Higher-order repository contained .gitignore file ignoring directory with another cloned repository.
Git blame is skipped because global .gitignore is being used - not the local one.
I'm fine if you leave it as it is.

**Comment by eamodio** [comment]
@krzysztof-balas Thanks for figuring it out! Trying to fix this will probably be quite involved (or hurt performance), but since I am only using the .gitignore file for better performance (avoiding blaming files that aren't going to be in the repo), I can add an advanced setting turn it off. Hopefully that will help.
