### ISSUE TITLE
Toggle Line Blame Annotations disappeared after last update

### ISSUE THREAD

**Issue by Mike-Now** [eamodio/vscode-gitlens#205]
- GitLens Version: 6.1.0
- VSCode Version: 1.18.0
- OS Version: Fedora 25

Steps to Reproduce:

1. Open VSode command prompt
2. Enter 'Blame' to search for commands with the word 'Blame' in it
3. There are no results from GitLens

**Comment by Mike-Now** [comment]
False alert. Started to work after restart.

**Comment by hvdklauw** [comment]
Yeah, had the same thing (a couple of times already), restart fixed it.. but the log showed it wasn't showing blame because according to GitLens the file was not tracked. 

And I saw some cache lines too, so maybe it's related to updating GitLens without restarting (just reloading) and the cache being invalid or something.

**Comment by eamodio** [comment]
Hrm, if either of you get this to happen again can you please post logs? I definitely want to get to the bottom of this.
