### ISSUE TITLE
Approx times for last update are wrong

### ISSUE THREAD

**Issue by NProtagoras** [eamodio/vscode-gitlens#212]
- GitLens Version: 6.1.2
- VSCode Version: 1.17
- OS Version: win 10 home

Steps to Reproduce:

1. Create a commit point with a date around a year ago
2. Try to use git lens to show when the last change happened

**Observed behavior**: The approximation is that last change was 1 month ago
**Expected behavior**: The approximation should show the last change was around 1 year ago

![image](https://user-images.githubusercontent.com/32260168/33241675-76ee7df8-d2d1-11e7-8d9c-4e2f3d4c0119.png)

**Comment by eamodio** [comment]
I unfortunately can't reproduce the issue, although I did have a VERY similar issue https://github.com/eamodio/vscode-gitlens/issues/185 which was fixed. Are you sure you are running the latest version of GitLens? Also, you reported that you are running 6.1.2, but vscode version 1.17 -- which isn't a valid combination, since 6.1.2 requires at least 1.18 to install and run properly.

Can you please verify the versions you are using and get back to me? Thanks!

**Comment by NProtagoras** [comment]
You're absolutely right, it seems like I didn't realize I was running some older version (5.x). On 6.2 the bug doesn't reproduce :)

Thanks for the quick answer, and for writing this extensions, it's really great 🥇

**Comment by eamodio** [comment]
Phew! Thanks! 😄
