### ISSUE TITLE
Suppress messages by default

### ISSUE THREAD

**Issue by rightaway** [eamodio/vscode-gitlens#222]
Would you consider suppressing these 2 types of messages by default? In my opinion they add nothing to the developer experience and feel 'spammy'. If no other extensions let us know by default that they've been updated or have a welcome message then that's the behavior that developers are used to.

```
    "suppressUpdateNotice": true,
    "suppressWelcomeNotice": true
```

**Comment by eamodio** [comment]
IMO there would be no purpose to suppressing the "welcome notice" by default -- the purpose is to welcome you the first time (and then not again). Though I agree that right now the welcome doesn't provide any really useful -- I had originally thought it would be the starting point of a setup "wizard", but I never got around to implementing that. I'll have to think more about either killing the welcome or adding a wizard.

As for the "update notice", you can either set the setting manually, or click the `Don't Show Again` button on the notification. I think this provides a reasonable balance for how different people work.

I **completely disagree** with you that they add nothing to the developer experience -- I try to provide pretty detailed changelogs and often add many new features, so this provides a way for users to know that there has been an update and to check out what's new. Now, for the "spammy" feel to them, I would somewhat agree, but currently I don't see a better alternative. I would love if there was some low-impact/passive mechanism for vscode to aggregate all extension updates into a single screen. So that I could still have the benefit of knowing there was an update, and getting to the changelog, but without pushing it in your face.

I would suggest voting/commenting on this issue: https://github.com/Microsoft/vscode/issues/21583, to have another mechanism for extensions to relay this information.
