### ISSUE TITLE
Investigate Reducing Startup Activation Time

### ISSUE THREAD

**Issue by zackschuster** [eamodio/vscode-gitlens#225]
- Extension Version: 6.3.0
- OS Version: Windows_NT x64 10.0.14393
- VSCode version: 1.19.0-insider

vscode added a new "Running Extensions" feature that gives you simple timing dumps for extension activation; i pulled the one for gitlens as it was rather large (time in `ms`):

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 876,
		"activateCallTime": 13,
		"activateResolvedTime": 122,
		"activationEvent": "*"
	}
}
```
compare with typescript's load times:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 326,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onCommand:workbench.action.tasks.runTask"
	}
}
```

and git:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 84,
		"activateCallTime": 16,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

obviously these (extremely simple & opaque) numbers are just for my (fairly powerful) 2015 macbook pro & aren't particularly painful, but given the size of the deltas here i suspect underpowered machines are hit even harder. 

assuming this is a "fixable" situation (e.g. it's not an issue with vscode APIs), i'm curious what could be done to improve this?

**Comment by imoby** [comment]
I'm also getting such a high start up time, 499ms. Triple of what some of the other highest extensions I have installed.

**Comment by eamodio** [comment]
I've released a new [GitLens 7 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.0.1-beta) which switches to use webpack for a bundled and minified build. I'm seeing a ~16%+ reduction in the startup time (not great, but not nothing either). Please try it out and see how it performs for you. Also keep an eye out for issues, because there could always been fun edge cases lurking in the minification.

/cc @zackschuster @imoby @niemyjski @Philip-Trettner

Also I'm quickly running out of ideas for reducing things further, so any help from the community would be greatly appreciated.

**Comment by VMBindraban** [comment]
I am getting a startup activation of 974ms. 

- Extension Version: 7.0.0
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.0

**Comment by eamodio** [comment]
@VMBindraban please try the beta version mentioned above in https://github.com/eamodio/vscode-gitlens/issues/225#issuecomment-352631213

**Comment by VMBindraban** [comment]
With the beta version; after a soft-reload 650ms, hard restart of VSC 970ms.

**Comment by eamodio** [comment]
@VMBindraban Great -- thanks. While its still takes a bit, a roughly 30% improvement isn't bad ;)

**Comment by zackschuster** [comment]
@eamodio would it be possible to use a rollup build instead? i'm imagining lots of time being spent on closure handling with webpack's custom modules. (i'm willing to help with this)

**Comment by eamodio** [comment]
FYI, I've posted a new [beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.1.0-beta) with a much more substantial reduction in startup time and also package size. I swapped out some large dependencies with some tiny homegrown (borrowed) implementations. Because of that this will require quite a bit of burn in -- but so far things look pretty good, imo. :)

@zackschuster If you'd like to take a shot at that and report back on the savings I'm all 👂  😉

**Comment by eamodio** [comment]
@zackschuster I've added support for rollup bundling  (`npm run bundle-rollup`) with the last check-in to develop. In my timings it is very close, though I'd say slightly worse than webpack, and its build times are WAY worse. If you have any other ideas (or want to tweak the rollup config) let me know.
