### ISSUE TITLE
Display codelens to the right of the editor screen

### ISSUE THREAD

**Issue by yeboahnanaosei** [eamodio/vscode-gitlens#263]
<h3>TAKE A LOOK AT THE PICTURES</h3>

- GitLens Version:    7.5.7
- VSCode Version:   1.19.3
- OS Version: :point_down: 
> elementary OS 0.4.1 Loki
> Based on Ubuntu 16.04.3 LTS
> Linux kernel 4.13.0-32-generic

Steps to Reproduce:

1. Open any file under source control
2. Codelens appears directly on top of line 1

**THIS IS THE CURRENT SITUATION**  
![gitlens-current-situation](https://user-images.githubusercontent.com/22800157/35472541-e23888d4-0368-11e8-83d3-e3b48903d10c.png)

**SUGGESTED APPROACH**  
![gitlens-float-right-with-suggestion](https://user-images.githubusercontent.com/22800157/35472544-f67f2442-0368-11e8-8e9b-f1ef0c48f2cd.png)

NB: Thanks so much for this great work! :+1:

**Comment by eamodio** [comment]
Thank you for you kind words and your suggestion. Unfortunately vscode doesn't support rendering code lens anywhere else other than where you currently see it. If you feel like this is a feature you'd like to see, I'd recommend opening an issue on the vscode repo asking for that support.

Closing this because until vscode can support this, there is nothing GitLens can do. Sorry.

**Comment by skube** [comment]
I guess the shifting down of code by a single line when codeLens is enabled (`"gitlens.codeLens.enabled":true,`) is also something that can't be avoided/fixed?

**Comment by eamodio** [comment]
@skube Correct there is nothing that GitLens can do to control that (other than turning the code lens off). Code lens by nature of how it is rendered cause the lines to move down (because lines are basically being added), but it should keep the current line where it was. So depending on the behavior it could be a vscode issue. FYI, I've opened https://github.com/Microsoft/vscode/issues/41968
