### ISSUE TITLE
Feature request: Enable heatmap by default when each file is opened

### ISSUE THREAD

**Issue by rbadapanda** [eamodio/vscode-gitlens#289]
I like the un-obtrusive nature of the heatmap.
Also, more I like it to be ever present, when I am looking for regressions in unfamiliar code base.

Would it be possible to create a settings which when set, enable heat map on each opened file? Currently it is only on-demand and per file.

[Enhancement Request]
[Just a thought]
Also how about, in this mode, if we draw the heatmap on the scrollbar itself ?

Thx!

**Comment by eamodio** [comment]
The next GitLens release will add support for controlling how annotations are toggled &mdash; for each file individually or for all files at once

As for supporting the heatmap on the scrollbar, I don't feel like that would work out well, because the scrollbar doesn't really give you a 1-to-1 mapping to individual lines. So it would be hard to really tell the age of a line other than the current one.

**Comment by rbadapanda** [comment]
Hi Eric,
Thanks for adding the support for showing the heatmap per window.

I agree with your point that the heatmap on the scrollbar will not show a 1-to-1 mapping to individual lines. so it cannot _replace_ the heatmap on left. However it can give me a summary for the whole file at a glance. So could it be a good feature addition?

**Comment by eamodio** [comment]
Mind opening a separate feature request for that? I don't think it is something I will be able to get into the next release, but will think about for a future release.

**Comment by rbadapanda** [comment]
Thanks for entertaining the req.

I opened [Feature Req #297](https://github.com/eamodio/vscode-gitlens/issues/297)   for the same.

**Comment by coder543** [comment]
The heatmap still disappears the moment I start typing, so I'm not sure this has really been fixed. It would be nice to have this feature on permanently!
