### ISSUE TITLE
Commit info tooltip duplicated for current line when blame is enabled

### ISSUE THREAD

**Issue by rhys-vdw** [eamodio/vscode-gitlens#29]
![image](https://cloud.githubusercontent.com/assets/822105/22813414/88884988-ef9f-11e6-9d68-49f74e029d2d.png)

I'm guessing it's shown once for the left annotation, and once for the one on the right.

**Comment by eamodio** [comment]
@rhys-vdw yeah it is -- While I *should* be able to conditionally turn it off on the right (i.e. the active line) one, I can't conditionally turn off the left one.  But the reason I actually left both in as ugly as it is, was because the right annotation is richer since it does a query for full commit log message (multiline) rather than the summary (single line - first 50 chars). And I unfortunately can't get the full commit message without going line by line, which would be prohibitively expensive.

I'm not sure which is worse. Any thoughts?

**Comment by eamodio** [comment]
Maybe I could do hack, where if we are in blame annotation mode and there is less than 50 characters in the commit message, then assume the left is good enough and hide the right. So you would still end up with duplicates but only when the data was actually different.

**Comment by rhys-vdw** [comment]
> [...] the right annotation is richer since it does a query for full commit log message (multiline) rather than the summary.

Is this when the cursor touches the line, or when the popup opens? Because I've also noticed a bit of lag when holding up/down since last update. I suspect it's caused by the active line annotation (but haven't confirmed yet).

Is it possible to only get the full commit message when the popup opens, regardless of the mode? That seems ideal, but I haven't at all looked at your implementation.

**Comment by eamodio** [comment]
It is when the cursor touches the line -- sounds like I might need to defer it until right after to not hold up movements.

Not as far as I can tell -- the decorators don't seem to provide a way to give it a promise or any other way to detect that the work should be done.

**Comment by rhys-vdw** [comment]
@eamodio You can probably just debounce the active line annotation so that it appears when the cursor is at rest - nobody can read at key repeat speed anyway. :) Sorry to mix two issues together here.

**Comment by eamodio** [comment]
@rhys-vdw yup -- just implemented that, helps quite a bit. Also made sure to track the current line, so column changes don't waste time :)

**Comment by rhys-vdw** [comment]
Just updated. That's much better - love your work. 👍
