### ISSUE TITLE
gitlens.showLineBlame

### ISSUE THREAD

**Issue by Stralos** [eamodio/vscode-gitlens#292]
`"gitlens.showLineBlame": false`
is not working, and it's impossible to disable inline blame annotations.

- GitLens Version 8.0.2:
- VSCode Version: 1.20.1
- OS Version: macOS High Sierra 10.13.3 

Steps to Reproduce:

1. Install gitlense
2. open VSCode config (command + ,)
3. paste "gitlens.showLineBlame": false
4. No profit.

https://github.com/eamodio/vscode-gitlens#current-line-blame
this is out of date.

**Comment by eamodio** [comment]
Sorry for the confusion -- that `gitlens.showLineBlame` isn't a setting, it is the id of the command (I include the id in the docs, so that you can setup keybindings). You can execute that command from the command palette -- *GitLens: Show Line Blame Annotations*.

The setting you are looking for is [`"gitlens.currentLine.enabled": false`](https://github.com/eamodio/vscode-gitlens#current-line-blame-settings). But you can also just use the built-in interactive Settings UI -- by running *GitLens: Open Settings* from the command palette

It looks like this:
![settings](https://user-images.githubusercontent.com/641685/36484018-e63520a6-16e5-11e8-856a-458e82dce9f3.png)

**Comment by eamodio** [comment]
Hopefully this answers your question, if not please re-open.
