### ISSUE TITLE
Need an explanation / legend for explorer icons

### ISSUE THREAD

**Issue by batjko** [eamodio/vscode-gitlens#305]
I can't find this in the big README or any related issues, so how can I find out what these icons mean?

![selection_762](https://user-images.githubusercontent.com/7287076/37148745-767abc5a-22c3-11e8-9a7a-b11cca764b01.png)

**Comment by eamodio** [comment]
They are avatar images pulled from the Gravatar service based on the e-mail address of the committer. If the e-mail address isn't registered with Gravatar then a fallback image is generated by Gravatar (unique per e-mail address).

You can toggle them on/off in the interactive settings editor. Check/uncheck the use avatars checkbox.

**Comment by batjko** [comment]
Ah, Gravatar... 
For a lot of people who use VSCode professionally, most commits will be done with their company email addresses, likely not associated with Gravatar accounts. 

But even if they do have some, these tiny color blobs/shapes are completely unrecognizable. I wonder if anyone gets some good use out of this feature?

Anyway, thank you for the kind explanation @eamodio! 👍

**Comment by eamodio** [comment]
Yeah for that case it definitely makes them less useful, but I would still suggest they are more useful than not having them. Since the avatars are consistent for an e-mail address you can still identify who committed what by looking at the generated avatar. 

You can also control the style of the fallback Gravatars by setting `gitlens.defaultGravatarsStyle` &mdash; See
https://github.com/eamodio/vscode-gitlens#general-settings
