### ISSUE TITLE
Default Settings Get Added Automatically

### ISSUE THREAD

**Issue by abdelrahmanrifai** [eamodio/vscode-gitlens#336]
`gitlens.advanced.messages` defaults get appended to the end of my user settings file everytime I remove it and restart vscode.

![gitlens](https://user-images.githubusercontent.com/4334778/38456396-be234fbc-3a84-11e8-8fb6-8c9d50b3eb22.gif)

Is that a normal behavior?

**Comment by eamodio** [comment]
Yes, it is normal, as GitLens is keeping track of messages that should be suppressed. It is ugly that I have to store them in the settings, but I used to store them in localstorage and ran into many issues where users would report that messages kept showing up, etc (because of underlying bugs in vscode's localstorage access). Honestly I've thought about consolidating them into a single entry (bit flags, or something) but then they would be harder to manually tweak.

**Comment by abdelrahmanrifai** [comment]
Thanks for your prompt response @eamodio, excuse me but I didn't understand the need for adding them to the user settings in case they are the same as in the defaults settings and I didn't customize anything?

**Comment by eamodio** [comment]
They aren't all defaults, the `suppressShowKeyBindingsNotice` is set to true once you have seen it. I will think about this more to change the data format, so it is less verbose. Although, it still will add a `gitlens.advanced.messages` entry.
