### ISSUE TITLE
Feedback on sensible defaults

### ISSUE THREAD

**Issue by mratsim** [eamodio/vscode-gitlens#353]
- GitLens Version: 8.2.4
- VSCode Version: 1.22.1
- OS Version: OSX

I tried GitLens once one month ago, removed it quickly due to the unsensible default, retried it and spend some time to reconfigure it. Here is my feedback.

- Overloading `Cmd + Shift + /` is bad. That's how I do `\` on a Mac with a French keyboard and probably lots of over international keyboard layout. That alone made me uninstall GitLens the first time. This should not be the default.
- The blame, author, history inline with the code are a huge focus distraction. As a developer, I want to focus on code but by default GitLens steal that focus. There are other way to show that ondemand: hovering over the line number for example, but don't display anything when I'm just hovering to fix code, copy-paste or anything.

**Comment by eamodio** [comment]
`cmd+shift+/` is not the default. The default is chord `cmd+alt+g /` unless you change the `gitlens.keymap` setting, which allows for quick control over all GitLens keybindings -- can set it to `none` if you want to control the keybindings yourself.

While I (and many others) disagree that those features are a distraction, I provide many easy ways to control the behavior to be custom tailored to your needs. GitLens provides many settings (easily configured using the GitLens settings editor -- `GitLens: Open Settings` from the command palette) to control ever part of the UI and also provides commands to toggle them back on -- on-demand -- as well. GitLens 8.3 also provides a new `mode` ability which allows you to predefine custom modes for GitLens -- `Zen`, `Reviewing`, etc -- which can easily be switched in and out of. So you might have all the "distractions" off normally, but switch into `Reviewing` mode which would turn many of them back on because they are helpful in that context.

I hope those options help. But if you have specific other requests please feel free to open individual issues for them. Thanks!
