### ISSUE TITLE
Current line annotations are hidden when debugging

### ISSUE THREAD

**Issue by hejianghu** [eamodio/vscode-gitlens#382]
- GitLens Version: 8.3.2
- VSCode Version: 1.23.1
- OS Version: macOS 10.13.2

Steps to Reproduce:

1. open the debug mode of VSCode
2. focus any line of a git repository file
3. the change information of this line could not appear
4. close the VSCode's debug mode and the information shows up

It's not a big problem, but a little frustrating...

**Comment by eamodio** [comment]
This is by design because the vscode debugging experience can also add decorations to the end of the lines (variables, etc) and GitLens can conflict with them. You can manually toggle them back on during a debugging session by using the `Gitlens: Toggle Line Blame Annotations` command from the command palette.

Please let me know if that work-around isn't enough, and I can probably add a setting to stop turning off the annotations when debugging.

**Comment by DaleHe** [comment]
@eamodio ok, thank you a lot!

**Comment by rugglcon** [comment]
That workaround is fine, but it would be a lot more convenient to have a setting that won't stop line annotations when in debug mode rather than having to do that everytime. Not sure how easy that would be for you to add, and also sorry for commenting on this closed issue. 

Let me know if that's at all possible or if you'd like some help.
