### ISSUE TITLE
Add a way to hide avatars in hovers

### ISSUE THREAD

**Issue by gigi206** [eamodio/vscode-gitlens#432]
Hello,

If I use gitlens without Internet access ![](https://image.ibb.co/ijHVkT/git.png)

There is a way to hide the icon ?

I see only the variable gitlens.defaultGravatarsStyle but there is no option to set none ?

Thank you :)

**Comment by eamodio** [comment]
As far as I know (other than the avatars) all the GitLens features should work. As for the avatars, there is not any online/offline detection nor is there a way to turn them off completely.

I'm hesitant to bother with online/offline detection, mainly because its a pain and imo doesn't really offer enough value. Although, I think having an overall setting to turn off avatars could be useful, so I will look into adding that as a feature.

**Comment by eamodio** [comment]
I'm going to change this to to just reflect the additional setting request.

**Comment by eamodio** [comment]
Added in 8.5
