### ISSUE TITLE
display extra gitlens in vue file with vetur

### ISSUE THREAD

**Issue by beeplin** [eamodio/vscode-gitlens#50]
When working together with vetur (vscode's officially recommended vue plugin) https://github.com/octref/vetur/issues/87, .vue files <style> part has extra gitlens displays:

![image](https://cloud.githubusercontent.com/assets/13058150/23818266/a48679a6-0634-11e7-8a54-1df31d78b573.png)

If using other vue support plugins such as`vue` or `vue-component` there is no this issue. Simply renaming .vue file to .html file doesn't show the extra gitlens either. This happens only with vetur.

**Comment by eamodio** [comment]
@beeplin this is by design -- GitLens uses the symbol information provided by vscode to add its CodeLens (and extensions can extend/provide this symbol information). So the Vue extension must be providing a symbol for those classes.

You can control the behavior of the CodeLens via a few GitLens configuration settings (you can find the documentation for each setting here: https://github.com/eamodio/vscode-gitlens#extension-settings):

`gitlens.codeLens.location`
`gitlens.codeLens.locationCustomSymbols`
`gitlens.codeLens.languageLocations`

If you have any of the above set, please let me know how you have them configured.

Also if you upgrade to v2.12.1, you can also set `"gitlens.advanced.codeLens.debug" = true` which will add debug information into the CodeLens themselves (symbol name, line range, etc). If you turn that on, and send a screenshot I can help you configure your settings appropriately.

**Comment by beeplin** [comment]
thanks. I will feedback to the author of vetur.

**Comment by octref** [comment]
Hey I'm working on vetur.

VSCode added symbols for html/css in Feb release:

https://code.visualstudio.com/updates/v1_10#_html

![image](https://cloud.githubusercontent.com/assets/4033249/23963502/d9ce21e4-0987-11e7-9699-378f938bc8d5.png)

If this breaks for vetur, it must be breaking for html too.

@beeplin Would you mind setting `gitlens.codeLens.locationCustomSymbols`? Seems this would fix the problem as @eamodio suggested.

**Comment by eamodio** [comment]
@octref sorry -- I definitely wasn't suggesting anything was wrong in vetur -- nor do I consider this something "broken" in GitLens. GitLens allows you to configure the CodeLens how ever you want given enough provided symbols from vscode/extensions.

But since `css` in `html` now add a symbol of `class` (which I consider to be a container type symbol) it will render with CodeLens by default (since the default is to render CodeLens at the document and "container" level). I've already added specific default overrides for `json`, `css`, `scss`, `less` to only render at the document level. I probably should just add `html` and `vue` to that.

@octref what is the language type for vue?

**Comment by octref** [comment]
No worries! Thanks for fast response.

The whole document is language type vue. Each embedded region has embedded language type such as `vue-html`, `css`, `scss`, `less`, `javascript`, etc.

![lang](https://cloud.githubusercontent.com/assets/4033249/23965844/b9142ff4-098f-11e7-9ee5-18ea8917d37f.gif)

**Comment by eamodio** [comment]
@beeplin can you try the following setting:
```
"gitlens.codeLens.languageLocations": [
                        {
                            "language": "html",
                            "location": "document"
                        },
                        {
                            "language": "vue",
                            "location": "document"
                        },
                        {
                            "language": "json",
                            "location": "document"
                        },
                        {
                            "language": "css",
                            "location": "document"
                        },
                        {
                            "language": "scss",
                            "location": "document"
                        },
                        {
                            "language": "less",
                            "location": "document"
                        }
                    ];
```
And let me know if that resolves the issue for you? If so, then I will add those into the defaults for the next release.

**Comment by beeplin** [comment]
@eamodio thanks for the quick response! Yes, this setting resolve my issue perfectly.

**Comment by eamodio** [comment]
@beeplin great -- look for that to be in the defaults of the next release and you'll be able to remove those explicit settings

**Comment by eamodio** [comment]
@beeplin it's now in 2.12.2

**Comment by octref** [comment]
Thanks a lot. gitlens looks pretty useful. I'll give it a try this weekend.
