### ISSUE TITLE
  How to configure dateformat options?

### ISSUE THREAD

**Issue by tryy** [eamodio/vscode-gitlens#532]
I configured like this

> "gitlens.statusBar.dateFormat": "YYYY-MM-DDTHH:mm:ss"

But it doesn't seem to work.

**Comment by eamodio** [comment]
That format is correct, but since GitLens shows dates in a relative format by default, you need to also set another setting.

Set `"gitlens.defaultDateStyle": "absolute",` to cause **all** dates in GitLens to be shown in an absolute format, which will cause the status bar to use your new date format.

If you don't want to affect all dates you can control the status bar only by setting:
`"gitlens.statusBar.format": "${author}, ${date}",` or something with `${date}` in it rather than `${ago}`

Hope that helps.
