### ISSUE TITLE
Open binary file 

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [eamodio/vscode-gitlens#541]
Can you add an option to open binary files? i.e. set the ways to open binary file in user-setting (including open in vscode in another tab) and open it by right-click the file in gitlens sidebar.  For me it's mostly pdf files and they can be opened in vscode, but sometimes other file formats might be needed.

**Comment by eamodio** [comment]
@Turgon-Aran-Gondolin Can you try this with the [GitLens 9 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v9.0.0-beta) release to see if you still have the issue? I have completely rewritten how GitLens provides file content to vscode and _should_ be able to support any file type vscode itself can open.

**Comment by eamodio** [comment]
In theory GitLens should be providing the raw file contents to vscode and then vscode applies its magic to figure out how to deal with that file (and this is basically using the same vscode code that is used for opening real files).

For the files it didn't work on (older commits), can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

As for the `Open Revision` command -- since vscode doesn't natively support pdf any extension providing that support I think would need to know about GitLens revision uris. Although from a quick look at the Latex extension, it detects the opening of pdf by language id -- and vscode doesn't provide me a way of specifying that, at the same time though it should be detected like it was an actual file. I'll need to do a bit more research into this.

**Comment by Turgon-Aran-Gondolin** [comment]
Thanks for your response! The log reads "file not found":

> Error: cannot open file:///home/path/to/file Detail: File not found (file:///home/path/to/file)

An additional problem is, when I open file from new commit, with msg level set to debug, an additional file called `extension-output-#3` is opened alongside my file. The log is 

> [2018-11-28 06:41:14:940] [29b] GitService.getRepoPath — e=Uri(file:///home/huangys/Github/QM-OPE/Dirac/Dirac-Draft.pdf)
> [2018-11-28 06:41:14:940] [29c] GitService.getRepository — e=Uri(file:///home/path/to/file.pdf), t={"skipCacheUpdate":true}
> [2018-11-28 06:41:14:941] [29d] GitService.isTracked true • 0 ms — e=/home/path/to/file.pdf, t=/home/home/path/to, i={"skipCacheUpdate":true}
> [2018-11-28 06:41:14:941] [29c] GitService.getRepository completed • 0 ms
> [2018-11-28 06:41:14:941] [29b] GitService.getRepoPath completed • 0 ms
> [2018-11-28 06:41:14:941] [29e] GitService.getRepository — e=GitUri(file:///home/path/to/file.pdf repoPath=/home/path/to)
> [2018-11-28 06:41:14:941] [29e] GitService.getRepository completed • 0 ms
> [2018-11-28 06:41:14:941] [29f] GitService.isTracked true • 0 ms — e=GitUri(file:///home/path/to/file.pdf repoPath=/home/path/to/)
> [2018-11-28 06:41:15:767] [2a0] RepositoriesNode.onActiveEditorChanged
> [2018-11-28 06:41:15:767] [2a0] RepositoriesNode.onActiveEditorChanged completed • 0 ms
> [2018-11-28 06:41:15:767] [2a1] FileHistoryTrackerNode.onActiveEditorChanged
> [2018-11-28 06:41:15:767] [2a2] FileHistoryTrackerNode.triggerChange
> [2018-11-28 06:41:15:767] [2a3] FileHistoryView.refreshNode — e=FileHistoryTrackerNode
> [2018-11-28 06:41:15:767] [2a4] FileHistoryTrackerNode.refresh
> [2018-11-28 06:41:15:767] [2a1] FileHistoryTrackerNode.onActiveEditorChanged completed • 0 ms
> [2018-11-28 06:41:15:767] [2a4] FileHistoryTrackerNode.refresh completed • 0 ms
> [2018-11-28 06:41:15:767] [2a3] FileHistoryView.refreshNode completed • 0 ms
> [2018-11-28 06:41:15:767] [2a2] FileHistoryTrackerNode.triggerChange completed • 0 ms

Since pdf file is not natively supported by vscode, I need to select `open it anyway` sometimes, and in the selection page (where vscode tells you it's a binary file thus not supported blabla, and if you want to open it anyway), everything seems fine but when I click `open it anyway`, the extension-output page popped up. I'm not sure if it's normal behavior or a bug.

**Comment by eamodio** [comment]
@Turgon-Aran-Gondolin Does this still happen with GitLens 11?
