### ISSUE TITLE
How can I Stage a specific change and commit it with a message ?

### ISSUE THREAD

**Issue by parsalotfy** [eamodio/vscode-gitlens#563]
I read the document and search for **commit** and **stage** but I couldn't find a way to stage a change and commit it like the native git extension of Visual studio Code
I would like to hide the native VSCode Source control and use Gitlens instead but as I could not find the way to **stage and commit a specific change** , the git lens extension is not comfortable for me.
Please let me know if there is a way ( Without Command Pallete ! )
Thank you.

**Comment by eamodio** [comment]
GitLens is not a replacement for the built-in Git extension, nor is it trying to be. GitLens and the built-in Git are complementary and for some things GitLens even relies on the built-in Git to provide some features.

In GitLens 9, I have added some more support for common, e.g. you can now stage files from the GitLens repositories view.

**Comment by parsalotfy** [comment]
Please Add commit in GitLens 9 too 🥇 
Thanks for answer 👍

**Comment by eamodio** [comment]
Committing is something that I feel the built-in git handles very well -- I don't see what GitLens could bring to the table to improve upon it without attempting to fully replace it (which I am not interesting in doing).

**Comment by igreg** [comment]
I understand that GitLens is not trying to replace the built-in features but as a user of both, I have to admit that I have to constantly switch between the two because of the arbitrary decisions that were made during their development to implement or not such and such feature in such and such way.

I appreciate GitLens increasingly every day, I am just sad that it can't be the only interface I have to use when committing my changes. My preference is to use when available a single product as it is usually quicker and simpler. I prefer to reserve my cognitive energy to writing code.

Just another perspective on the tradeoffs of the current situation.

**Comment by eamodio** [comment]
@igreg what are the types of things that you'd rather manage via GitLens vs the built-in git support? Also one way I personally deal with switching between the 2 is moving the GitLens Repositories view to the Source Control sidebar (rather than on the GitLens sidebar), so that there is much less "switching"

**Comment by igreg** [comment]
Ohh very neat. I was expecting visual studio code to allow such thing; I stand corrected. Seems an acceptable and reasonable compromise. Thank you @eamodio.

**Comment by gee4vee** [comment]
@eamodio how do you switch the GitLens repositories view to the Source Control sidebar?

**Comment by oklas** [comment]
This issue is about commit feature but [resolution](https://github.com/eamodio/vscode-gitlens/issues/375#issuecomment-389932168) is:

> GitLens is not a replacement for the built-in Git extension, nor is it trying to be. GitLens and the built-in Git are complementary and for some things GitLens even relies on the built-in Git to provide some features.

I created [new one](https://github.com/eamodio/vscode-gitlens/issues/1135) which is not same as this and does not asks additional feature that already exists in `built-in git` but instead it asks a commit for another repos that are not available for commit from `built-in git` (#1135).

**Comment by oklas** [comment]
This issue is about commit feature but [resolution](https://github.com/eamodio/vscode-gitlens/issues/563#issuecomment-443450053) is:

> GitLens doesn't provide that ability -- that is provided by the built-in Git extension in vscode, which you can get to from the Source Control activity

I created [new one](https://github.com/eamodio/vscode-gitlens/issues/1135) which is not same as this and does not asks additional feature that already exists in `built-in git` but instead it asks a commit for another repos that are not available for commit from `built-in git` (#1135).
