### ISSUE TITLE
Linter no longer works over file diffs

### ISSUE THREAD

**Issue by edugarcam** [eamodio/vscode-gitlens#594]
- GitLens Version: 9.2.0
  
- VSCode Version: 1.30.0
- OS Version: Linux x64 4.19.8-arch1-1-ARCH 

More or less a week ago linter, spell checker and sonnar (in my case) stop works when i am reviewed commit differences.

Is it a normal behaivor?

Thanks in advance!

**Comment by eamodio** [comment]
Sadly this expected since GitLens changed from using temp files on disk to using a virtual FileSystemProvider. This change was for many reasons (fixes many bugs, opens up many new features), but this one of the consequences of it.

Although for some of those tools, they can "learn" to target not just files (i.e. documents using the `file` scheme) and could target GitLens' virtual files which use the `gitlens` scheme

**Comment by edugarcam** [comment]
Ouch! Thank you for the answer
