### ISSUE TITLE
How to get Gitlens to view workspace hosted by SSHFS?

### ISSUE THREAD

**Issue by DarthSpock** [eamodio/vscode-gitlens#609]
I have a server I remotely connect to using SSHFS for a project I'm doing that makes use of the FileSystemProvider API to do ssh://  paths. How do I get Gitlens to show this workspace?

**Comment by eamodio** [comment]
Are you using a vscode extension to support ssh files?

**Comment by DarthSpock** [comment]
Yes the extension is actually called SSHFS, not to be confused with the FUSE one. Link to project: https://github.com/SchoofsKelvin/vscode-sshfs

I'm running on Win 7 but remote into a Fedora Server that's used among other purposes for my dev work before getting pushed to BitBucket.

**Comment by eamodio** [comment]
Does the built-in git support in vscode work with that setup?

**Comment by DarthSpock** [comment]
I'm not sure. I haven't been successful in getting it to read the path. I'm unable to create a Samba share so I'm totally reliant on the extension to directly manipulate from Windows.

**Comment by eamodio** [comment]
Yeah, unfortunately I don't think it can work, since both the built-in vscode git and GitLens shell out to git itself to do all of the work. So the git process would need to be able to have access to the repo/fs itself.

**Comment by eamodio** [comment]
Closing as this currently isn't possible given the current level of file system support

**Comment by havardl** [comment]
Hey @WSLUser, did you ever get to the bottom of this?

**Comment by WSLUser** [comment]
I had filed an issue with VS Code https://github.com/Microsoft/vscode/issues/66046 but I also found https://github.com/Microsoft/vscode/issues/68808 which now has the on-deck tag on it. Probably because the issue writer provided a bit more details except in that case it was filed for the use case of debugging (which is why I requested VS Code itself tackle the issue instead of extension authors.)     Technically this extension just needs to take a look at the filesystemprovider API and implement the necessary support for ssh:// paths but as indicated above, git is not the only thing affected.
