### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by officialsanjaysharma** [eamodio/vscode-gitlens#650]
- Issue Type: `Performance`
- Extension Name: `gitlens`
- Extension Version: `9.4.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/sanjay/eamodio.gitlens-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by eamodio** [comment]
@officialsanjaysharma or anyone else who experiences this -- can you please attach the profile? Without that I can't do anything about it.

**Comment by yasuyuki** [comment]
I met a similar problem.
I created a gist with cpu profile.
https://gist.github.com/yasuyuki/e1c552d2ebb348a2f54dc4375e69f04d

**Comment by eamodio** [comment]
I've looked into that profile and I don't see anything from GitLens in there -- can you please capture a new profile the next time this happens?

**Comment by udox-cameron** [comment]
I am having the same problem it seems to be happening on my Mac when I've started it with Reopen windows when logging back in. If I quit and open VS Code it fixes itself.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by mic345** [comment]
This is how it looks on the process explorer, with a new `git blame` process starting every few minutes. I really hope you manage to solve this one, as it renders this wonderful extension useless.

I turned off `gitlens.currentLine.enabled`, and will let you know if it helped. Otherwise, if you have a workaround for disabling the functionality that causes this, it would be extremely helpful!

Good luck 👍

![Desktop screenshot (32)](https://user-images.githubusercontent.com/36601023/63301485-42a24f00-c2a0-11e9-9b8a-8e24ca46a007.png)

**Comment by eamodio** [comment]
@mic345 can you please open a new issue for this issue and please be sure to provide logs for when you see this issue? Thanks!
