### ISSUE TITLE
line history loses the line range after first click

### ISSUE THREAD

**Issue by enerjazzer** [eamodio/vscode-gitlens#662]
- GitLens Version: 9.5.1
- VSCode Version: 1.31.1
- OS Version: Linux

Steps to Reproduce:

1. select a range of lines
2. go to Line History, see the list of commits affecting these lines
3. click any commit

Expected results: the Line History doesn't change, allowing you to click other commits for the range and see the changes for the selected range of lines (see how CLion does that, Git->Show History for Selection)

Actual results: Line History loses the range and doesn't show all commits anymore, instead it shows only of the lines in the selected commit and (I guess) a list of commits corresponding to that line.

**Comment by eamodio** [comment]
That is basically by design, since automatic tracking is enabled by default. Although you can toggle on/off the automatic tracking at anytime:

![image](https://user-images.githubusercontent.com/641685/53197437-376bb080-35e8-11e9-9c7c-64824fc25c7e.png)

And the view won't change until you manually refresh or unpause tracking.

Hope that helps.

**Comment by speed-oss** [comment]
@enerjazzer if you think this was helpful, consider adding a reward to this issue using speedoss.com to support the issue solver for their work :)
