### ISSUE TITLE
Can't upgrade to latest version

### ISSUE THREAD

**Issue by localhost61** [eamodio/vscode-gitlens#666]
I first searched here and in the _readme.md_ why I couldn't upgrade from v8.5x to v9.5.1 and didn't find any answer.

Then I tried to uninstall and reinstall and got same version, VScode didn't warn for a new version of GitLens.
The reason seems due to the fact _**I was running VScode v1.2.1**_. Once I upgraded VScode to current v1.3.1.1 it offered me to upgrade GitLens.

Sorry if I make the Question and the Answer but it's weird and thought it may help another one that me to now the solution ;-)

**Comment by eamodio** [comment]
Yeah, this isn't GitLens specific. It is just way vscode handles extension versioning -- an extension says what the minimum version of vscode that is needed (because of apis or features) and vscode will only allow you to install the latest version of an extension compatible with your vscode version. It would indeed be nice if vscode made that more clear in the UI as to why you might not have the latest version (and could be an opportunity for them to suggest upgrading 😄). Would you might opening an issue on the vscode repo with your experience?

**Comment by localhost61** [comment]
I anticipate what they will tell me, you're the first one that ask, nobody change default settings:
- Extensions:Auto Update
- Update:Enable Windows Background Updates
- Update:Channel
;-)

**Comment by eamodio** [comment]
@localhost61 thanks for reporting that -- I added my 2c too ;)

**Comment by localhost61** [comment]
5000 pending issues in VScode !!! Wahoo ! I didn't had heart to add one :-/
