### ISSUE TITLE
Cannot type backslash after installing "Git lens"

### ISSUE THREAD

**Issue by mdelapenya** [eamodio/vscode-gitlens#68]
- GitLens Version: 3.4.5
- VSCode Version: 1.11.2
- OS Version: MacOS Sierra 10.12.3

Steps to Reproduce:

1. Install Git Lens
2. Open a file under a git repo
3. Type `\` at any line

Expected behavior: `\` is written
Actual behavior: `\` is not written

**Comment by eamodio** [comment]
@mdelapenya I can't reproduce this, nor can I fathom how GitLens could effect this -- do you have some key configuration setup for `\`?

**Comment by mdelapenya** [comment]
No, but I uninstall the plugin and everything works as expected.

Let me grab the computer and send my plugins​ list

**Comment by eamodio** [comment]
Is there anything else special about you setup? Do you have any customize key commands for GitLens?

**Comment by mdelapenya** [comment]
No, I don't have any special key command.

The top header info message appears just hitting `\` with GitLens enabled.

Here is a capture of my plugins:

<img width="1439" alt="screen shot 2017-04-18 at 19 25 19" src="https://cloud.githubusercontent.com/assets/951580/25144021/c822e45c-246c-11e7-95fc-8baea95ac6aa.png">

**Comment by eamodio** [comment]
@mdelapenya I'm really at a loss here. Do you have any special keyboard layout or app (like karabiner or something?)? And you definitely don't have any occurrences of `gitlens` in your `keybindings.json` file? 

If you open the GitLens extension and switch to the `Contributions` "tab" do you see `\` listed?

**Comment by mdelapenya** [comment]
Hey @eamodio, I'm sorry to say no to all, no keyboard layout here nor gitlens contribution 😢 
<img width="1049" alt="screen shot 2017-04-19 at 08 48 51" src="https://cloud.githubusercontent.com/assets/951580/25166738/18d9eaba-24dd-11e7-83f2-af05f006edf8.png">
<img width="1049" alt="screen shot 2017-04-19 at 08 49 07" src="https://cloud.githubusercontent.com/assets/951580/25166739/18f0ae26-24dd-11e7-8d64-cf103d523085.png">

**Comment by eamodio** [comment]
@mdelapenya hrm. I still have no clue how this could happen. Are you on a US keyboard layout? What other else is on your `\` key? I'm actually on vacation this week so I won't really be a Le to do much more until next week. Maybe we can screen share or something

**Comment by mdelapenya** [comment]
I'm using Spanish keyboard.

Yeah, we can do that once you are back

Thanks!

**Comment by eamodio** [comment]
@mdelapenya can you take a screenshot of the command palette if you type `GitLens` into it (with an open editor for a file in a git repo). I want to see what vscode thinks the keybindings are since they should show up there. Can you also take a screenshot of the GitLens contributions page (in vscode) -- make sure to scroll down to the `Commands` section (that also will show the keybindings).

I'm not sure if it is related, but I've found these vscode issues that could be related:
https://github.com/Microsoft/vscode/issues/4084
https://github.com/Microsoft/vscode/issues/14984
https://github.com/Microsoft/vscode/issues/23386

**Comment by mdelapenya** [comment]
Hi Eric, here I attach the screenshots:

### Command palette
<img width="1437" alt="command palette" src="https://cloud.githubusercontent.com/assets/951580/25472361/45c0007e-2b2b-11e7-91f8-a26d5290f335.png">

### Commands contributions
<img width="1009" alt="screen shot 2017-04-27 at 09 22 07" src="https://cloud.githubusercontent.com/assets/951580/25472364/45d3d072-2b2b-11e7-9eea-41b622a096dd.png">
<img width="1011" alt="screen shot 2017-04-27 at 09 22 26" src="https://cloud.githubusercontent.com/assets/951580/25472362/45c31638-2b2b-11e7-988f-47ed4e62d699.png">
<img width="1010" alt="screen shot 2017-04-27 at 09 22 44" src="https://cloud.githubusercontent.com/assets/951580/25472363/45cefc3c-2b2b-11e7-82d5-3f6ff2bc0578.png">
<img width="1014" alt="screen shot 2017-04-27 at 09 23 06" src="https://cloud.githubusercontent.com/assets/951580/25472360/45bd9442-2b2b-11e7-9bf0-e303df785c85.png">

**Comment by eamodio** [comment]
@mdelapenya can you try the new beta here: [v3.5.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta)? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

I'm still very much at a loss to how this is happening, but there have been quite a lot of changes in the latest version and with any luck maybe it will help.

**Comment by mdelapenya** [comment]
Hey @eamodio, with 3.5.0-beta it works as expected!

Thank you very much for your work here :)

Closing...

**Comment by eamodio** [comment]
Excellent! Thank you for your patience!

**Comment by jjabba** [comment]
I'm having the same problem using a Swedish keyboard layout. Backslash in this layout is achived by hitting **alt-shift-7** which I guess is the same as git-lens's "search-by-message" shorthand. Looking for a way to change or add an alternative when swedish keyboard is used.

**Comment by nuttmeister** [comment]
Same error with GitLens 8.0.2 using Swedish layout on mac. Trying to do backslash will just output the git search box. It's weird that the default keyboard layout for GitLens would override the default backslash binding for macs. ALT+SHIFT+7.

**Comment by eamodio** [comment]
Please open the GitLens settings (run *GitLens: Open Settings* from the command palette) and jump to *Keyboard Shortcuts* and change to either the `chorded set` or `custom set`.

In the next GitLens release, I am thinking about switching to the `chorded set` by default to avoid these issues

**Comment by jjabba** [comment]
@eamodio 
I agree that overlapping shorthand-conflicts should be handled by visual studio code. But for me, as well as @nuttmeister it's taking precedence over regular character input (i.e. for the _\_ character on a Swedish keyboard layout. I'm guessing since this is not a shortcut, it's not detected as a conflict by visual studio code. 

@nuttmeister  My solution for now is to add these lines to keybindings.json:

{ "key": "shift+alt+7", "command": "-gitlens.showCommitSearch", "when": "gitlens:enabled" }

**Comment by eamodio** [comment]
Yeah, this has been a long standing issue and I will make the change to make the chorded set the default -- since it was "designed" to not conflict with any normal typing.

Yeah, you can definitely just remove any conflicting binding manually, or just switch GitLens to use a different keybinding set (or no set if you want to control it all manually)
