### ISSUE TITLE
Implement an easy way to add a new remotes.

### ISSUE THREAD

**Issue by Megalomaniak** [eamodio/vscode-gitlens#694]
As I brought up in https://github.com/eamodio/vscode-gitlens/issues/612#issuecomment-477242751 it would be nice to be able to just right-click on remotes in gitlens side panel and see a menu item for `Add new remote`. Currently there's only an entry for `Refresh`.

![GitLens_Remotes](https://user-images.githubusercontent.com/3162126/55317446-334d7100-5479-11e9-8f7e-eabcf8dcbb89.png)

For now I've resorted to following this guide from github to add upstream remote from vsc terminal:
https://help.github.com/en/articles/configuring-a-remote-for-a-fork

It certainly works, however it does feel a bit dissatisfying having to resort to using the terminal for this, what with everything else one can do through GitLens already. I certainly think that the proposed feature fits the overall design of GitLens well.

**Comment by Snukii** [comment]
Yes please

**Comment by zaboyle** [comment]
I'm new to open source, but I'm working on implementing a feature like this! Hope to make a PR in the near future

**Comment by eamodio** [comment]
@zaboyle awesome! Please let me know if you have any questions. And don't hesitate to open a PR early.

**Comment by zaboyle** [comment]
Hi @eamodio ! I actually do have a question: I think i found a resource on [this website](https://code.visualstudio.com/api/extension-guides/overview) to help with creating the "Add Remote" option that should appear when right-clicking, but I am having trouble figuring out how to create a `Command` object for this Git command. If you can point me in the right direction, I would greatly appreciate it!

**Comment by eamodio** [comment]
So there a quite a few steps to this, but I'll try to lay out the basics and will use the `gitlens.views.checkout` command as the "template" to follow.

So first you'll need to add a new command for `gitlens.views.addRemote` similar to `gitlens.views.checkout`
https://github.com/eamodio/vscode-gitlens/blob/345be49d7b31f8dfd8cf2f60fadee0bc2fed17d3/package.json#L2367-L2376

Then you add a "placement" for the command like below, but it should be `gitlens.remotes` rather than `gitlens.branch`
https://github.com/eamodio/vscode-gitlens/blob/345be49d7b31f8dfd8cf2f60fadee0bc2fed17d3/package.json#L4255-L4260

Then you register a callback for when the command is executed, like:
https://github.com/eamodio/vscode-gitlens/blob/345be49d7b31f8dfd8cf2f60fadee0bc2fed17d3/src/views/viewCommands.ts#L116-L117

And then implement a new `addRemote` method

That is the basics of it.

**Comment by zaboyle** [comment]
Awesome, thank you for your help! I'll work on that today and this weekend :thumbsup:

**Comment by zaboyle** [comment]
Thanks again for your help @eamodio ! I made a PR for this in #802 , let me know if there's anything I need to change!

**Comment by eamodio** [comment]
Added in v9.93 -- thanks @zaboyle!
