### ISSUE TITLE
Navigate to Github?

### ISSUE THREAD

**Issue by Korporal** [eamodio/vscode-gitlens#74]
Does this tool allow us to navigate right to the Github page for some commit? If we provided the following

base organization URL,
repo name (almost always the same name as the repo folder on local disk)
commit ID

Then you can build the URL of the commit and have VS open a browser window and see the commit IN Github, does it do anything like this?

**Comment by eamodio** [comment]
@Korporal That is currently supported today -- using the `Open Commit in Remote` command -- or via the commit details quick pick menu. I'm currently working on adding a `Open Branch in Remote` command (though there is support for the current branch on the branch/repository history quick pick menu) as well as `Open Repository in Remote`.

The reason it is called `Remote` is because it supports GitHub, GitLab, BitBucket, VS Team Services. And if your repository is configured with more than one, you will get a quick pick menu to pick the remote you want.

**Comment by eamodio** [comment]
@Korporal if that addresses your question, please close this issue -- thanks!

**Comment by eamodio** [comment]
@Korporal FYI, you can try the new beta here: [v3.5.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta)? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

It adds `Open Branch in Remote` and `Open Repository in Remote` commands.

**Comment by eamodio** [comment]
Closing this -- please reopen if you feel there is something I missed.
