### ISSUE TITLE
Disabling "Current Line: Scrollable" causes line hover to not show

### ISSUE THREAD

**Issue by thijsputman** [eamodio/vscode-gitlens#783]
Issue Type: <b>Bug</b>

Setting `gitlens.currentLine.scrollable` to `false` causes the informative hover (with `gitlens.hovers.currentLine.over` set to `annotation` - its default setting) to not show.

Setting `gitlens.hovers.currentLine.over` to `line` resolves the issue, but only triggers the hover on the actual code, not the GitLens generated annotation at the end of the line.

Enabling `gitlens.currentLine.scrollable` makes the hover appear as expected.

Extension version: 9.8.2
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by eamodio** [comment]
Unfortunately I don't believe this can be fixed. The issue is that setting `gitlens.currentLine.scrollable` to `false` removes the decoration (what vscode calls it) from the document flow (using `position: absolute`) which also causes vscode to not be able to get events for hovering over that element (vscode doesn't provide any apis for extensions to get events on decorations directly -- so the current way is kind of a hack, but requires the decoration to take up space in the document).

Sorry.

**Comment by thijsputman** [comment]
No worries. Thanks for the quick response and the additional info (and the great vscode extension 😉)!
