### ISSUE TITLE
Update the sidebar icon

### ISSUE THREAD

**Issue by johnletey** [eamodio/vscode-gitlens#784]
With the new vscode icons being released soon 🎉 (https://github.com/microsoft/vscode/issues/8017) ... the icon definitely needs to be updated to match the new icons' styles!

**Note:** I already have an icon designed and will submit a PR soon!

**Comment by johnletey** [comment]
@eamodio How does this look:

<img width="335" alt="Screen Shot 2019-07-10 at 6 46 36 AM" src="https://user-images.githubusercontent.com/30328854/60938916-7e7be900-a2de-11e9-9fb3-15a64b187ff0.png">

I will submit a PR once you give me the green light!

**Comment by johnletey** [comment]
@eamodio I'm currently designing updates for the rest of the icons in the extension! Stay tuned!

**Comment by bcongiusta** [comment]
Also consider this icon as well.

![image](https://user-images.githubusercontent.com/48673777/60948425-848abd80-a310-11e9-881b-c79dd50b97b8.png)

**Comment by iyashpal** [comment]
Please consider this icon as well. it doesn't look good with the new icon set of vs code.

![image](https://user-images.githubusercontent.com/19922707/60948636-02e75f80-a311-11e9-93a4-e37487dacf88.png)


Thanks

**Comment by johnletey** [comment]
@iyashpal Not to worry ... I am going through and updating **all** of the icons throughout the package so that everything looks great for the new vscode release!

You can check out my progress here: [Figma](https://www.figma.com/file/d2JR6axIc4bsXOEsCOJfdChF/gitlens-icons)

I have already updated quite a few icons already and am working hard on the others so that we can have a PR up soon!

**Comment by misolori** [comment]
@johnletey the stash all icons are referenced here:

https://github.com/eamodio/vscode-gitlens/blob/84363ec5aca56e62e407965c2e55f62f17edc59f/package.json#L2281-L2288

**Comment by eamodio** [comment]
@johnletey Awesome -- thanks for taking this on! The activity bar icon looks good at that size, but I'd need to see it in product to really know. Are the strokes the same width as the vscode icons?

**Comment by johnletey** [comment]
I'm not quite sure ... they are 2px strokes @eamodio ... what are the stroke sizes for the vscode icons @misolori?

**Comment by eamodio** [comment]
@johnletey also for quite a few of the icons, I lifted directly from vscode, so we should just lift the new versions directly

**Comment by johnletey** [comment]
I understand ... and actually, that's exactly what I've been doing @eamodio

**Comment by misolori** [comment]
@johnletey icons have a 1.5px border width and have a bevel edge:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/35271042/61244700-a664b580-a6ff-11e9-8761-f184432c2f49.png">

**Comment by johnletey** [comment]
Thanks, @misolori ... how does this look @eamodio?

<img width="341" alt="Screen Shot 2019-07-16 at 7 26 41 AM" src="https://user-images.githubusercontent.com/30328854/61265896-1ecc8480-a79b-11e9-88ec-0506f5f18262.png">

[Figma](https://www.figma.com/file/d2JR6axIc4bsXOEsCOJfdChF/gitlens-icons?node-id=1%3A2)

**Comment by eamodio** [comment]
@johnletey it looks great there, but in-product it looks a bit wonky
![image](https://user-images.githubusercontent.com/641685/61266456-f3797380-a761-11e9-8edf-3e629947eff5.png)

I'm assuming that is because of some (mis-)alignment to the pixel grid? I'd also suggest moving the bottom-most dot, up a tad to give it a little more space between it and the circle

**Comment by johnletey** [comment]
@eamodio I have moved up the bottom-most dot a tad bit ... here it is now:

![Screen Shot 2019-07-16 at 7 43 52 AM](https://user-images.githubusercontent.com/30328854/61266681-94d1eb00-a79d-11e9-8dd9-880d82fce9b3.png)

The icon itself and everything is all aligned in the pixel grid! 🤔

PS. What vscode theme are you using? 👀

**Comment by eamodio** [comment]
Hrm, the spacing at the bottom is better, but now it looks chunkier for some reason:
![image](https://user-images.githubusercontent.com/641685/61266750-47d12300-a763-11e9-8f49-34910c542698.png)

I'm using my Dark Amethyst theme: https://marketplace.visualstudio.com/items?itemName=eamodio.amethyst-theme

**Comment by johnletey** [comment]
@eamodio Just some minor updates here ... how does it look now?

<img width="546" alt="Screen Shot 2019-07-16 at 7 47 42 AM" src="https://user-images.githubusercontent.com/30328854/61266794-1a559b00-a79e-11e9-9e9c-0f0a22d442f4.png">

**Comment by eamodio** [comment]
Still chunky: 
![image](https://user-images.githubusercontent.com/641685/61266863-b7dfa900-a763-11e9-8d9f-54bf57c572c1.png)

Do you see the same in vscode?

**Comment by johnletey** [comment]
I'm actually not running this in local development

**Comment by johnletey** [comment]
For anyone that is following the progression of this issue, I have updated the activity bar icon (and it is not showing up chunky when in local development)

Update commit: https://github.com/johnletey/vscode-gitlens/commit/e1f2f51ee22c058c8ac7637d3fc5857d78c12e80

**Comment by jonbp** [comment]
Going to throw my two cents in here as i think the proposed sidebar icon isn't quite there yet.

Expanding on the work started by @johnletey, I've redrawn the icon to ensure that the strokes match the 1.5px width as mentioned by @misolori. My reworked icon also utilises the space inside the circle a little better.

I've also omitted the first small tail of the git icon, i feel it simplifies the icon a bit to be more uniform with the other activity bar icons without losing a sense of what it actually does.

Here's a side by side of the 2 icons for comparison:

![comparison](https://user-images.githubusercontent.com/3267483/62721032-39dd8d80-ba03-11e9-971a-b8f32377b51d.png)

I'd appreciate some feedback and could do with testing on retina displays (I have no way of testing this ☹️)

[Download](https://github.com/eamodio/vscode-gitlens/files/3482790/gitlens-activitybar.zip)

**Comment by johnletey** [comment]
@jonbp Thanks for recommendation ... and personally, I like yours better! What do you think @eamodio?

**Comment by eamodio** [comment]
Looks great! Thanks @jonbp & @johnletey!

I have to say at first, I wasn't an immediate fan of losing the connecting tail since it deviates from the GitLens logo
![GitLens Logo](https://gitlens.amod.io/favicon.ico)

But after looking at it a bit, I do like its clean feel. I do wonder, what if it had a very subtle hint of a tail?

**Comment by bcongiusta** [comment]
Hi there,

Who is this and why am I in this thread?

Kind Regards,

Ben Congiusta

On 9 Aug 2019, at 5:29 am, Eric Amodio <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks great! Thanks @jonbp<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonbp&data=02%7C01%7C%7C7a39c3ac1a1d47f63bd108d71c36bc39%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637008893719753576&sdata=zRbeP%2F4oeQwZINJXMjgNbmPAnpJhUDDEvp4Zw4wsgHs%3D&reserved=0> & @johnletey<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnletey&data=02%7C01%7C%7C7a39c3ac1a1d47f63bd108d71c36bc39%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637008893719763575&sdata=PI0Aqz1zq53zB6gkKrvcPS9phD6rmEVtIp%2FzR7UqZ2I%3D&reserved=0>!

I have to say at first, I wasn't an immediate fan of losing the connecting tail since it deviates from the GitLens logo
[GitLens Logo]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F87910822bd16d0d5addca12e40226049bf784e43%2F68747470733a2f2f6769746c656e732e616d6f642e696f2f66617669636f6e2e69636f&data=02%7C01%7C%7C7a39c3ac1a1d47f63bd108d71c36bc39%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637008893719773580&sdata=jx9TeoMBLME46rdUMiWtjAZDaT2YKIm8BhtTPNrJN1g%3D&reserved=0>

But after looking at it a bit, I do like its clean feel. I do wonder, what if it had a very subtle hint of a tail?

**Comment by johnletey** [comment]
I have utterly no clue @bcongiusta ... GitHub error?

**Comment by bcongiusta** [comment]
Maybe. Could you please remove me?

Kind Regards,

Ben Congiusta

On 9 Aug 2019, at 6:27 am, John Letey <notifications@github.com<mailto:notifications@github.com>> wrote:


I have utterly no clue @bcongiusta<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbcongiusta&data=02%7C01%7C%7C5cca4872e75f4e959e9808d71c3ec55e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637008928231388816&sdata=HiEpeaFDE2FwObg7kY7UEt8IekO%2BkJ2zaHuYkApINUo%3D&reserved=0> ... GitHub error?

**Comment by eamodio** [comment]
@bcongiusta unfortunately no, you have to unsubscribe yourself. You can click the mute thread link at the end of the email or follow the view it on GitHub link and then click the unsubscribe button on this page.

**Comment by bcongiusta** [comment]
Done-thank you.

________________________________

**Comment by jonbp** [comment]
I've added the tail back into the logo and i think it looks pretty good now!

Here's a screenshot:

![Screenshot from 2019-08-10 18-40-07](https://user-images.githubusercontent.com/3267483/62825101-62e65580-bb9e-11e9-902d-17af8af26a15.png)

[Download](https://github.com/eamodio/vscode-gitlens/files/3489162/gitlens-activitybar.zip)

**Comment by johnletey** [comment]
@jonbp Is it centred? It doesn't look centred when I look at the screenshot

**Comment by jonbp** [comment]
I had to push the contents down a touch to accommodate the new small tail. I don't think it looks unbalanced, though I'm open to scrutiny!

**Comment by johnletey** [comment]
No ... now that I look at it again, it looks fine to me

Great job @jonbp

**Comment by eamodio** [comment]
It's awesome! Thank you both so much!!

**Comment by mrmckeb** [comment]
This looks great, well done all. Will this be in the next release?

**Comment by johnletey** [comment]
Hopefully yes @mrmckeb, but it's up to @eamodio

**Comment by I0F** [comment]
Why does it have to have the exact same git pattern as the Git logo. Why not make it more artsy and more _lensy_ if thats a word

![GitLens](https://user-images.githubusercontent.com/18104031/63188497-d4704900-c061-11e9-86ab-b8fac2a37e7d.png)

Anyway I think all the lines having same width, the tail connecting to the outer circle, and the other circles having holes in them looks much cleaner

![GitLens2](https://user-images.githubusercontent.com/18104031/63188496-d4704900-c061-11e9-8b81-4550b752bb8a.png)

The tail of the @jonbp version doesn't have the same width as the other lines, why?

[GitLens.zip](https://github.com/eamodio/vscode-gitlens/files/3510657/GitLens.zip)

**Comment by eamodio** [comment]
FYI for anyone following along this work is progressing in Figma: https://www.figma.com/file/LFzZXPci3T5tui8O53KyWCGo/GitLens-Icons

**Comment by LukasPolak** [comment]
@eamodio when will be icon updated? Thanks!

**Comment by eamodio** [comment]
When v10 ships -- which is Soon™ 😄

**Comment by misolori** [comment]
I realize that the discussion around the icon has already passed (I wasn't actively engaged), but just to drop my two cents, it feels like the new icon doesn't fit so well with the rest of the VS Code icons:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/35271042/65360955-b5ac2780-dbb6-11e9-86e5-489c4527ce6c.png">

- The circle around the icon feels odd/constraining
- Since the tail piece is removed, it's hard to decipher what metaphor of the icon is

I guess I was hoping for something a little simpler like:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/35271042/65361397-41728380-dbb8-11e9-8375-d6874656477e.png">


I'm sure we'll all get used to the new icon over time but thought I'd drop this feedback here in case this ever gets revisited.

**Comment by eamodio** [comment]
@misolori Hrm, part of me is a bit concerned about familiarity by changing the icon too much -- the circle is quite recognizable. At the same time, I can see what you are saying (but I also think that will fade over time). I do worry though with your rendering about the closeness to the SCM icon -- I feel like you could easily mistake one for the other.

But, I am definitely open to suggestions and improvements

**Comment by misolori** [comment]
@eamodio that's fair, my suggestion was based on the original git logo anyways. Just thought I'd throw it out there. I'm sure you'll get the immediate "who moved my cheese" comments (we got our fair share on the VS Code icons 😉).

**Comment by eamodio** [comment]
Hehe -- yeah, omg there was so many of those 😉

**Comment by johnletey** [comment]
@eamodio Thank you very much for continuing my work and updating all of the icons! I have really been appreciating the new icons!

One thing that I've been noticing, is that the circle around the activity bar icon isn't as thick as the official icons. For example, here is the official activity bar icon for the [vscode-pull-request-github](https://github.com/microsoft/vscode-pull-request-github) extension (which @misolori updated):

![Shot 2019-09-24 at 09 49 47](https://user-images.githubusercontent.com/30328854/65497408-1c308e80-deb2-11e9-91fe-53e300a25262.jpg)

So, I've gone into Figma and updated the thickness of the circle from `1.25` to `1.5` (which is what @misolori says that he uses for the icons) so that the icon now matches the official ones. Here is what it looks like now:

![Shot 2019-09-24 at 09 57 34](https://user-images.githubusercontent.com/30328854/65497585-6580de00-deb2-11e9-89db-a9c695cf409d.jpg)
