### ISSUE TITLE
Branch diff against master shows incorrect files in two-dot mode

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#797]
_Originally reported in https://github.com/eamodio/vscode-gitlens/issues/293#issuecomment-513853506._

[v9.9](https://github.com/eamodio/vscode-gitlens/blob/master/CHANGELOG.md#990---2019-07-21) introduced new behavior for comparing with other branch:

![Screen Recording 2019-07-22 at 15 06 05_05 (1)](https://user-images.githubusercontent.com/101152/61640457-a9cae480-ac9d-11e9-90bf-e123db5a10c1.gif)

The number of commits is correct but the files shown are incorrect.

**Comment by borekb** [comment]
Thanks, works beautifully!

**Comment by borekb** [comment]
This might be another related bug. I tried to open the same comparison in the **Compare** panel and it produces a different set of results:

<img width="443" alt="Screenshot 2019-07-23 at 14 46 23" src="https://user-images.githubusercontent.com/101152/61713425-d263e480-ad58-11e9-9f57-ecf0c2bc24a3.png">

(In the upper part of the screenshot, there's a node from the **Repositories** pane which displays the correct numbers.)

**Comment by eamodio** [comment]
@borekb That behavior while a bit confusing is working correctly. Basically the issue is that when using the 2-dot (range) syntax the order of the compare matters, i.e. `211-component-for-complex-l18n..master` vs `master..211-component-for-complex-l18n`.

So in the repository compare, I am always showing `<branch/tag/ref-you-choose>..<current-branch>`, because you want to see the changes in your current branch as compared the chosen "base". In your case that is: `master..211-component-for-complex-l18n`

While the 2nd compare (in the compare view), the order is determined by how you select what to compare (which you can easily swap). In your case that is: `211-component-for-complex-l18n..master`

If you swap the compare, so it says _Comparing master to 211-component-for-complex-l18n_ the 2 comparisons will match.

Given that, you can certainly argue that what I display in the repo compare is somewhat misleading, but to me it felt odd/wrong to switch the display order (e.g. to say `master <--> 211-component-for-complex-l18n` rather than `211-component-for-complex-l18n <--> master`), because `211-component-for-complex-l18n` is the current branch.

**Comment by borekb** [comment]
Oh I see, it's indeed quite a UX challenge then. How about unifying the two this way:

- Both use the icon (as in the Repositories panel) to save space.
- Both use _white_ for the current branch.
- Both use _gray_ for the other comparison target.
- Both use the same format which looks like this:
    - <img height="16" src="https://img.icons8.com/ios-glyphs/24/000000/compare-git.png"> `master..211-component-for-complex-l18n`
    - <img height="16" src="https://img.icons8.com/ios-glyphs/24/000000/compare-git.png"> `master...211-component-for-complex-l18n`
    - <img height="16" src="https://img.icons8.com/ios-glyphs/24/000000/compare-git.png"> `211-component-for-complex-l18n..develop`

It doesn't look that good without colors but if the current branch stood out, maybe this could work? I'm generally happy when it's clear from the UI what I'm looking at.

One problem with the above is what to do when `master` in the examples above is some long ref. Maybe it could be substituted with the word "base" or something.

**Comment by eamodio** [comment]
@borekb FYI, in v9.9.3, I've reverse the order of the comparisons in the _Compare_ view, so now they will match the repository compare -- so everything will be consistent and hopefully work as would be expected.

**Comment by borekb** [comment]
Very nice, thank you!
