### ISSUE TITLE
Support Tree Indent value

### ISSUE THREAD

**Issue by esemlabel** [eamodio/vscode-gitlens#804]
Git Lens currently not respect "Workbench > Tree: Indent" value.
<img width="252" alt="VSCODE Workbench Tree Indent" src="https://user-images.githubusercontent.com/17903845/62121274-f4ff7b80-b2cb-11e9-9a50-55589e0acb0c.png">

**Comment by eamodio** [comment]
That setting and the tree rendering is controlled by VS Code. In the stable build of VS Code, no custom views honor that setting (since it is only supported with their new tree implementation), but in the insiders build the custom views have been upgraded to the new tree implementation and now honor this setting.

So once VS Code 1.37 ships (pretty soon) this will be supported.
