### ISSUE TITLE
Output of file history view has buggy styling

### ISSUE THREAD

**Issue by mattgabor** [eamodio/vscode-gitlens#825]
- GitLens Version: 9.9.3
  
- VSCode Version: 1.37.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open vscode
2. Install gitlens
3. Open history view

![image](https://user-images.githubusercontent.com/5590876/63451072-40530880-c3f8-11e9-9e47-e9096977fda4.png)

**Comment by eamodio** [comment]
@mattgabor Hrm, haven't seen anything like that (other than a vscode bug in the insiders build a long time ago). This *shouldn't* be possible because of how the vscode api is, so I would recommend opening an issue with vscode itself about it. And do you have any custom font-sizing, line-height settings?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
