### ISSUE TITLE
Refresh button on Compare With Branch view is not working

### ISSUE THREAD

**Issue by angelo-mollame-2** [eamodio/vscode-gitlens#847]
Issue Type: <b>Bug</b>

Clicking on the Refresh buttons (both at the level of the individual comparison, and at the level of the entire Compare pane) does nothing.

Extension version: 9.9.3
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

**Comment by angelo-mollame-2** [comment]
I installed a version from way back (9.4.0) and it works there.

**Comment by angelo-mollame** [comment]
@eamodio The Refresh button at the level of the individual comparison now works, but the Refresh button at the level of the entire Compare pane still doesn't.

**Comment by eamodio** [comment]
@angelo-mollame-2 ah, that is basically by design. The refresh at the top level, just causes everything below it to "repaint", but the refresh at the individual item level additionally causes it to re-query for its data.

**Comment by angelo-mollame** [comment]
@eamodio Hmm... but if I remember correctly, both Refresh buttons were working in the way I thought they were supposed to work, in version 9.6.3. I may be wrong, but that's what I remember. Was the design changed since that version?

**Comment by eamodio** [comment]
It could have worked differently before, I did a bunch of work to avoid re-query unless it was an explicit action. There we many cases before were queries could happen multiple times and depending on the query/compare it could be very expensive.

What is the use-case for needing to requery a set of compares?

**Comment by angelo-mollame** [comment]
I sometimes keep two or more comparisons open. For example, one against master, one against a target branch that I'm cleaning up. That global Refresh button allowed me to refresh all the comparisons in one click. Clicking on each individual Refresh button now requires multiple clicks, plus scrolling when comparisons show a lot of files.

On top of that (and even more importantly IMO), since it used to work before, there's the habit of just clicking on that global Refresh button, and relying on it. Now that that Refresh button doesn't refresh the comparisons anymore, I could come to the wrong conclusion about the current content of a branch, which could have a disastrous impact.

I don't think a global Refresh button that just repaints is useful. I'd rather not having it at all, than clicking on it and thinking that it's **actually** refreshing.

I think it used to work perfectly before. If performance is a concern, the user always has the choice of how many comparisons to keep around, so I don't see a problem there.
