### ISSUE TITLE
Display gitlens depending on cursor position

### ISSUE THREAD

**Issue by ackvf** [eamodio/vscode-gitlens#874]
By default, a file and every function/code block within the file is lensed.

I would prefer if the position of cursor controlled which function or code block displays references.

**Comment by eamodio** [comment]
While I think this is "technically" possible with the vscode api, the way code lens are handled this would cause a LOT of jumping in the document as you moved around -- which imo would be a very bad user experience. In addition this would be a large change to how code lens are handled in GitLens. Because of both of those issues, this isn't something I would support adding. Sorry.
