### ISSUE TITLE
Add autolink support (custom link detection in commit messages)

### ISSUE THREAD

**Issue by jonfen** [eamodio/vscode-gitlens#897]
The default points to the git repo on gitlab, but we use a separate redmine server to handle issues.

**Comment by eamodio** [comment]
Currently there really isn't a way to support this -- but I am planning on a more flexible version of the link detection feature that should allow this.

**Comment by eamodio** [comment]
Add the ability to create "autolinks" which will match patterns in commit messages and linkify them. For example, if a commit message contains `JIRA-123` then turn it into a link like `https://jira.github.com/issue?query=123`.

Ref: https://github.com/eamodio/vscode-gitlens/issues/346

**Comment by jonfen** [comment]
https://github.com/eamodio/vscode-gitlens#autolink-settings

Works great!

**Comment by Sigura** [comment]
I know it closed. But let me please describe one of use case because I'm sure - I'm not alone with this pain.

First thank you for your amazing work!

Precondition: we have a rule - add issue # to commit description (after subject\n\n).
Desired behavior: issue # at current line with link to our tracker

Partially it solved with [autolink](https://github.com/eamodio/vscode-gitlens#autolink-settings) (thanks again!)

My suggestions:

 * add `{issue}` template to `gitlens.currentLine.format` for first found link. It will looks like: `${author} • ${issue} ${message}`
 * show commit description in current line too after few seconds below it (without popup) and `gitlens.currentLine.inlineDetails` for those things

I know it not a main use case and I think it's bunch of work. That is why this message added to closed task. If you have not time or environment for this feature request, just skip it. If any idea or part of it close to you, that is nice for me too.

**Comment by eamodio** [comment]
@Sigura are you asking explicitly for GitHub issues? or something else?

**Comment by Noitidart** [comment]
Can autolink be configured based on workspace. If im in X workspace it should open autolink #<num> on github/repo/x?
