### ISSUE TITLE
File Blame Annotations lost after change focus on another file

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#92]
- GitLens Version: 4.1.0
- VSCode Version: 1.13.0
- OS Version: Win 10x64

Steps to Reproduce:

1. open in VSCode 2 files
2. turn on File Blame Annotations on first file
3. switch to second file and return to first one

Expected: first file still with Blame Annotations

Actual: first file without Blame Annotations

**Comment by eamodio** [comment]
This only works if the editors are in view -- since when an editor is out of view it get destroyed along with its state. While it is probably possible to keep track of this, I don't think it would be too easy (given the other craziness I have to do to manage the whitespace toggling. And we would only want to track it if the document is still open -- once you close it, the state should be reset.

While I'm not opposed to this behavior at all, I'm also not that interested in adding this type of feature. Although PRs are welcome.

**Comment by SailorMax** [comment]
Sorry, but PR from me currently is not possible. My knowledge of TS is not enough.

**Comment by eamodio** [comment]
I'm going to close this one - the blame annotation toggling is complex enough, I don't want to add even more complexity.
